apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-421-prod-1776410376
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 3fce2d4af6ff1ae57ce223d7f63fdafccdf19f86
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-3-ocp-421-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-421-1776388356
  data:
    version: 3.3.2
