apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-419-prod-1762938758
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 95084eabda471f4033ffb2af294b2d84e0b5c3b3
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-419
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-0-ocp-419-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-419-1762790908
  data:
    version: 3.0.0
