apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-417-1742491679
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: a03146f0828d8afb4affa75ba1e33dda99734f05
    konflux-release-data/ocp-version: ocp-417
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-417
  components:
    - name: rhoai-fbc-fragment-ocp-417
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:fc67c0954d0768849ec045d5bba4e92e83a566a66a2658e5d1f6b6dc75bb49a6
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 45201caffab9f5a2259d63e202005dae0086ec33