apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-415-prod-1744652125-1
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 4bbb418d43e0d6faccf341142795e17a868d9911
    konflux-release-data/ocp-version: ocp-415
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-19-ocp-415-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-415-1744118572
