apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-416-1749121685
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 0b3c214510dee2d21e85167bf17e8920c143eedd
    konflux-release-data/ocp-version: ocp-416
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-416
  components:
    - name: rhoai-fbc-fragment-ocp-416
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:90d8527bca920177ca8a66f58aeec5885eb9b8533747f62343fd5d1d3be492ef
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 081d53495b09047f9f9e91085ad91e023aa26307