apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1784218219
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 281b2b5fe490f515448fb0a29d33811811222d62
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:2b715738a70decefc147f6ced324149c4394e7c9e737393acf66f2275e84b1c3
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 552401a092380a5dae77328bcfb7f197b4b4cb59