apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-418-1784218219
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 281b2b5fe490f515448fb0a29d33811811222d62
    konflux-release-data/ocp-version: ocp-418
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-418
  components:
    - name: rhoai-fbc-fragment-ocp-418
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:9a3e3a4a999681d9cf50f9b5f02de55e6b26a52a5b92a4025f42310ee616e5fb
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 552401a092380a5dae77328bcfb7f197b4b4cb59