apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-418-prod-1755181013-1
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 0f408af87aac8d78dfc98697a9de6948dd1f43a6
    konflux-release-data/ocp-version: ocp-418
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-418
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-23-ocp-418-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-418-1755088033
  data:
    version: 2.23.0
