apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-419
    konflux-release-data/artifact-type: fbc
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/rbc-release-commit: 91c9e3fc764ff9ed954bfe793d8b167935e8ccbd
    test.appstudio.openshift.io/type: override
  name: rhoai-fbc-fragment-ocp-419-1772134826
  namespace: rhoai-tenant
spec:
  application: rhoai-fbc-fragment-ocp-419
  artifacts: {}
  components:
  - containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:7acb7a6f757773740ce8e14f066509c6f0c62651ef9648107102776621f2468e
    name: rhoai-fbc-fragment-ocp-419
    source:
      git:
        revision: 305fed5f633ed307849a76b17c4d7bcde8c901a0
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
