apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/rbc-release-commit: 91c9e3fc764ff9ed954bfe793d8b167935e8ccbd
    test.appstudio.openshift.io/type: override
  name: rhoai-fbc-fragment-ocp-421-1772134826
  namespace: rhoai-tenant
spec:
  application: rhoai-fbc-fragment-ocp-421
  artifacts: {}
  components:
  - containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:3e15de392db2d782948a031f02c78e11df5dc403ed59c0d1500790f1a48e3323
    name: rhoai-fbc-fragment-ocp-421
    source:
      git:
        revision: 305fed5f633ed307849a76b17c4d7bcde8c901a0
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
