apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-420-prod-1787855508
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 1d45f4d7c4dba3ba5caec2109e5e1a2da8a5f5d4
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-ocp-420-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-420-1787853778
  data:
    version: 3.4.4
