apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1782381920
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 3742fe0b679103d31dac4091cc2102273d6ff2f4
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:d1cfc3ed590e58b1dd28fb3edf79c85eb3ee0061720e8dd62f6005cdeeca9df1
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 4d38b4649e52d4ba5b4a8c30a853511375d34bba