apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1782381920
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 3742fe0b679103d31dac4091cc2102273d6ff2f4
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:66ae47f0c34b3e7319ea799a34e2aa2665a63c6523bc2648183e229b3555a85a
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 4d38b4649e52d4ba5b4a8c30a853511375d34bba