apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-420-prod-1777161042
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 6a2008826e49611e35a48774c1f657a209b82e4c
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-ocp-420-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-420-1777151239
  data:
    version: 2.25.6
