apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-420-prod-1782104124
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: e2a5cb14463a313ebd727f7109ee65972274896b
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-ocp-420-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-420-1781854664
  data:
    version: 3.4.1
