apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1789887166
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: aa48a24d378d81007593abd9823d41adb4943032
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:5f0df491e98be0dcb470c6f2904416c5f3ca7f31b487e6ae79dce0d80feb8b3d
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 5a000d40b43e18af5c1bf50c49de7ba856f9f024