apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1789887166
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: aa48a24d378d81007593abd9823d41adb4943032
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:177304517c5758378a19125b1b2244cfc4374246a5355babe9ed2a45fd122844
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 5a000d40b43e18af5c1bf50c49de7ba856f9f024