apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/rbc-release-commit: 91c9e3fc764ff9ed954bfe793d8b167935e8ccbd
    test.appstudio.openshift.io/type: override
  name: rhoai-fbc-fragment-ocp-420-1772732973
  namespace: rhoai-tenant
spec:
  application: rhoai-fbc-fragment-ocp-420
  artifacts: {}
  components:
  - containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:6b963998ca912ff8718028e1dd956d1e8aa3fab31204ff9daf5d8fc68ef650a2
    name: rhoai-fbc-fragment-ocp-420
    source:
      git:
        revision: 7a944e01e51347fdc2c3c1a7cc3b5b7ac5137443
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
