apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-419
    konflux-release-data/artifact-type: fbc
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/rbc-release-commit: 91c9e3fc764ff9ed954bfe793d8b167935e8ccbd
    test.appstudio.openshift.io/type: override
  name: rhoai-fbc-fragment-ocp-419-1772732973
  namespace: rhoai-tenant
spec:
  application: rhoai-fbc-fragment-ocp-419
  artifacts: {}
  components:
  - containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:d1fc3e1f6c9841093c408e151011dc2cbb03c58083b649bbd5492453283853d3
    name: rhoai-fbc-fragment-ocp-419
    source:
      git:
        revision: 7a944e01e51347fdc2c3c1a7cc3b5b7ac5137443
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
