apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1777151239
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 6a2008826e49611e35a48774c1f657a209b82e4c
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:6233b58205d832a84c7ca23a4ef9ab45deb0f82d701410d73d8483c03c68e7ee
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 77d20173e7c6f0d28cbd36679c8528c8f3f2627b