apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1777151239
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 6a2008826e49611e35a48774c1f657a209b82e4c
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:1442fddf3889925db42d84085175718073eeb4199c780978dc93e876198209b7
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 77d20173e7c6f0d28cbd36679c8528c8f3f2627b