apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-417-1777151239
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 6a2008826e49611e35a48774c1f657a209b82e4c
    konflux-release-data/ocp-version: ocp-417
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-417
  components:
    - name: rhoai-fbc-fragment-ocp-417
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:31f43bbee7aa41297af41fe04b89666af3e75717be065dcc47c76a384be19e3b
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 77d20173e7c6f0d28cbd36679c8528c8f3f2627b