apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-418-prod-1749659122
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 09ec727f6789b476672f17c177b4e41fede3e94b
    konflux-release-data/ocp-version: ocp-418
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-418
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-21-ocp-418-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-418-1749646336
