apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-417-1784063275
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 281b2b5fe490f515448fb0a29d33811811222d62
    konflux-release-data/ocp-version: ocp-417
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-417
  components:
    - name: rhoai-fbc-fragment-ocp-417
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:cdf5f3b1ac5c69770c39efaa126f72c883bd0da688f3c7d9b81a6c97704d4d9b
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: b9f86dc5ee8d2c4e4a146593ac54336531889f9a