apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-422-prod-1781711166
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 42edeba36844b5373317b11f2d88764b3706507b
    konflux-release-data/ocp-version: ocp-422
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-422
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-5-ea-1-ocp-422-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-422-1781285777
  data:
    version: 3.5.0-ea.1
