apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: ef8c0443c6e89ae92ac9e281029e2930726dcad4
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-22-1763704151
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-22
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:914112fc973f21e45a20182058286b4c13931c8ebc5492fb0acff83b3a1a5eaa
    name: odh-operator-bundle-v2-22
    source:
      git:
        revision: 0786ed7d4d30fd3024a96a83c5b27206c3cd4127
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel9@sha256:efe8a0ed3aeaf8f73c5b39723d3175a362d86e99cbd121b62a38d92461ade2dc
    name: odh-codeflare-operator-v2-22
    source:
      git:
        revision: 1074d813c802b24e608cb8b2a2cb469598321d34
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel9@sha256:bb186b1b98106295e8ee0ce8c83c1b82759ade13f03550390d39690c99df4708
    name: odh-dashboard-v2-22
    source:
      git:
        revision: 7029c609b7a02b766ce32c12e5fbbae8fb09bdc6
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel9@sha256:80f83c7f99096ce0e7dde9601ba59199890260d45c6907ff600aaad31e711069
    name: odh-data-science-pipelines-argo-argoexec-v2-22
    source:
      git:
        revision: 58f37e6e5d2392e1866bd4ad56124d10b0972e1d
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9@sha256:43a8d6dcc68297de45fa0c2b50ef8f21aec5edff81b3b84a5d08c1e2a320fe36
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-22
    source:
      git:
        revision: 58f37e6e5d2392e1866bd4ad56124d10b0972e1d
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel9@sha256:e8ead576bf2d42377ea72e7a137c6584eaeec4e7af89dff8fd99531555b53d15
    name: odh-data-science-pipelines-operator-controller-v2-22
    source:
      git:
        revision: e87c0dcbcc02291ec1ea26921ab3d46fea29c118
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-feast-operator-rhel9@sha256:3fa33fb9fd238dda3dd0dbc5243d0ec3e82083fb9ecf557a5f8a5b67afc77ba8
    name: odh-feast-operator-v2-22
    source:
      git:
        revision: 58673a71ac456a4ecc00271565a90e7f38bc4da6
        url: https://github.com/red-hat-data-services/feast
  - containerImage: quay.io/rhoai/odh-feature-server-rhel9@sha256:d5d52b368050d505183452f1d8b5170c86f7473fd869a886777d3bf7e48aad76
    name: odh-feature-server-v2-22
    source:
      git:
        revision: 3c044667284853a93c2ecffceae44758a2cd58da
        url: https://github.com/red-hat-data-services/feast
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel9@sha256:7e94b0aa823e7c531994f5f632e285b1decb1d670fb9d7dc8f8afdc9d34b8819
    name: odh-kf-notebook-controller-v2-22
    source:
      git:
        revision: 4b0ba55d22013f7f1284aa212607be01969bd300
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel9@sha256:9b1b6e929db26c98ace95a541f2ef95caf761894f32baaccabacaf541b630422
    name: odh-kuberay-operator-controller-v2-22
    source:
      git:
        revision: 0faa858ff15c99e2361f7af573637e403ad740f4
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel9@sha256:6e3afe7e4be47d487f448dddc6be021224264fb30d769e06b4014169005ff9a0
    name: odh-kueue-controller-v2-22
    source:
      git:
        revision: 2aee01021dc5f7b272ef6783819200e40110e8b1
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel9@sha256:8731a4e39783fb48645404b85491568e40259cd8f01cbdaf264d05a07627b0b9
    name: odh-ml-pipelines-api-server-v2-v2-22
    source:
      git:
        revision: d23dccc6b2d7c0e74013d1a8ad53a2034485b4cb
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel9@sha256:a86e1cf3d8256aea25f1d4557e5747b7e3b4f6e36af128fc8bcc68cc0c432352
    name: odh-ml-pipelines-driver-v2-22
    source:
      git:
        revision: d23dccc6b2d7c0e74013d1a8ad53a2034485b4cb
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel9@sha256:292dc31b93a35d0a14cd0204223d9b9f56d576ec8ca51baa75eafb09dadf14f4
    name: odh-ml-pipelines-launcher-v2-22
    source:
      git:
        revision: d23dccc6b2d7c0e74013d1a8ad53a2034485b4cb
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9@sha256:00a55eb4153348c785968a65391b5633ec7a13e11662a7dcf095088ffce15010
    name: odh-ml-pipelines-persistenceagent-v2-v2-22
    source:
      git:
        revision: d23dccc6b2d7c0e74013d1a8ad53a2034485b4cb
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-runtime-generic-rhel9@sha256:93cebe18839b0c806d63ff6090c74b6ebd8ed37e9bc307bd0889852a915992b2
    name: odh-ml-pipelines-runtime-generic-v2-22
    source:
      git:
        revision: dbc617440b2c61ce7df9ea11f43e7bb31f9f1bef
        url: https://github.com/red-hat-data-services/ilab-on-ocp
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9@sha256:29bf5b6e96db421abed20cee36df4e69de5cda4827e394c8b5c1b02270714220
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-22
    source:
      git:
        revision: d23dccc6b2d7c0e74013d1a8ad53a2034485b4cb
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel9@sha256:7c722d605c51e2f152ecca89f9134320cc4ace1cec55e522150ef5d9827aa2d0
    name: odh-mlmd-grpc-server-v2-22
    source:
      git:
        revision: 37b2db90eb68025457bfe726f78bd8264cfa4ef1
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel9@sha256:457df575f5289e2bfb3c300c310a4668fde8c931530f52da70193222c9b1e1a6
    name: odh-mm-rest-proxy-v2-22
    source:
      git:
        revision: 61921c47aaf3a6adcd0551693db4a583504b2a95
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel9@sha256:3ff83d0ea5071bf3e01d527df71b172e06b0cf97e0ace3e1861aa4cb63b7d15a
    name: odh-model-controller-v2-22
    source:
      git:
        revision: 46c472a293d2e007a6e2b6240518ecee22738d38
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel9@sha256:466e4ad536970d11b88cf33d8d765a7d379c8252b643097265eaef2e5930d6f3
    name: odh-model-registry-operator-v2-22
    source:
      git:
        revision: 921f4bc5378ff34fd1db8356bfddc76d5b0f57c8
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel9@sha256:84e6327b10f7ccee75c84d8c96a95c36c6ad14bac41785c2d8199e99dc129e53
    name: odh-model-registry-v2-22
    source:
      git:
        revision: 5e0efcb7f007b0a64a3d8d83e97c17f6f28f97ae
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel9@sha256:3b9ab0665c204439b2ce40d4a279e6af5e169aca9c092c23063b8907b7ddf8bd
    name: odh-modelmesh-v2-22
    source:
      git:
        revision: 4f5ef7f856e41b6d7c56bc4ec808180a35321c12
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel9@sha256:f1158ebb253b50b57592101e07ad56d71f3e307eed791caf6fbc45a6471a0251
    name: odh-modelmesh-runtime-adapter-v2-22
    source:
      git:
        revision: 165a22dad11cdc29740c20507f454bba684b5e2e
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel9@sha256:6d914de9930523a225628b86662c3f8a005696dce9ce2c54ce2059acb4834916
    name: odh-modelmesh-serving-controller-v2-22
    source:
      git:
        revision: fe7d80cbfca8c42f186d92c8657ef4c1945c7f5e
        url: https://github.com/red-hat-data-services/modelmesh-serving
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel9@sha256:6bdceed3b2a91120bba6bc130b671015b28a16acee1a48a1f09b7fcf16e3e1af
    name: odh-notebook-controller-v2-22
    source:
      git:
        revision: 4b0ba55d22013f7f1284aa212607be01969bd300
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel9-operator@sha256:e3674dff76cd8b23a5e96db3099f6d092cc74af48177af0e786310f59d717c3c
    name: odh-operator-v2-22
    source:
      git:
        revision: 8ed98f4fd864cc80ce01dad5be9ddcc3ad01c023
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel9@sha256:5c3b47ad3e5dab120892a5c05fea188499215b042648331c43446f80c848219e
    name: odh-training-operator-v2-22
    source:
      git:
        revision: a59fb2fc95b02e0f152ee660ac0aaa5c6488fb63
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel9@sha256:3038dad86bc403803c630511c3808ec35ddaa3260cc1280f8f4afbf538eb507d
    name: odh-trustyai-service-operator-v2-22
    source:
      git:
        revision: 5ffe8e1f01fbc7c825916e0f2a30272563645e12
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel9@sha256:4cff3dfda5dc12498ecca4176668cffb395d4d2fbad1eb6fdb740b737d7be357
    name: odh-trustyai-service-v2-22
    source:
      git:
        revision: 8923f81d3c14eed7ec1493cc8edda3872f68ed9a
        url: https://github.com/red-hat-data-services/trustyai-explainability
