apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-25-prod-1761134452-1
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 2800b48c01aeb448430418c9f66d03ba36eb99a6
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-25
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-components-prod
  snapshot: rhoai-v2-25-1760669391
  data:
    version: 2.25.0
    releaseNotes:
      synopsis: "RHOAI 2.25.0 - Red Hat OpenShift AI"
      topic: "Updated images are now available for Red Hat OpenShift AI."
      description: "Release of RHOAI 2.25.0 provides these changes:"
      solution: |-
        For Red Hat OpenShift AI 2.25.0, refer to the documentation linked below for detailed guidance on upgrading your cluster and applying this errata update. The documentation will be updated shortly to include information specific to this release.

        https://docs.redhat.com/en/documentation/red_hat_openshift_ai/
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_ai/
      cves:
        - key: 'CVE-2025-55163' # https://issues.redhat.com/browse/RHOAIENG-32580
          component: 'odh-modelmesh-v2-25'
      issues:
          fixed:
          - id: RHOAIENG-36329
            source: issues.redhat.com
          - id: RHOAIENG-36050
            source: issues.redhat.com
          - id: RHOAIENG-36027
            source: issues.redhat.com
          - id: RHOAIENG-35725
            source: issues.redhat.com
          - id: RHOAIENG-35716
            source: issues.redhat.com
          - id: RHOAIENG-35309
            source: issues.redhat.com
          - id: RHOAIENG-35141
            source: issues.redhat.com
          - id: RHOAIENG-35106
            source: issues.redhat.com
          - id: RHOAIENG-35105
            source: issues.redhat.com
          - id: RHOAIENG-35102
            source: issues.redhat.com
          - id: RHOAIENG-35041
            source: issues.redhat.com
          - id: RHOAIENG-35040
            source: issues.redhat.com
          - id: RHOAIENG-35031
            source: issues.redhat.com
          - id: RHOAIENG-34959
            source: issues.redhat.com
          - id: RHOAIENG-34929
            source: issues.redhat.com
          - id: RHOAIENG-34837
            source: issues.redhat.com
          - id: RHOAIENG-34827
            source: issues.redhat.com
          - id: RHOAIENG-34554
            source: issues.redhat.com
          - id: RHOAIENG-34517
            source: issues.redhat.com
          - id: RHOAIENG-34452
            source: issues.redhat.com
          - id: RHOAIENG-34409
            source: issues.redhat.com
          - id: RHOAIENG-34392
            source: issues.redhat.com
          - id: RHOAIENG-34375
            source: issues.redhat.com
          - id: RHOAIENG-34162
            source: issues.redhat.com
          - id: RHOAIENG-34158
            source: issues.redhat.com
          - id: RHOAIENG-34157
            source: issues.redhat.com
          - id: RHOAIENG-34156
            source: issues.redhat.com
          - id: RHOAIENG-34155
            source: issues.redhat.com
          - id: RHOAIENG-34086
            source: issues.redhat.com
          - id: RHOAIENG-33998
            source: issues.redhat.com
          - id: RHOAIENG-33997
            source: issues.redhat.com
          - id: RHOAIENG-33914
            source: issues.redhat.com
          - id: RHOAIENG-33901
            source: issues.redhat.com
          - id: RHOAIENG-33727
            source: issues.redhat.com
          - id: RHOAIENG-33701
            source: issues.redhat.com
          - id: RHOAIENG-33553
            source: issues.redhat.com
          - id: RHOAIENG-32991
            source: issues.redhat.com
          - id: RHOAIENG-32969
            source: issues.redhat.com
          - id: RHOAIENG-32965
            source: issues.redhat.com
          - id: RHOAIENG-32955
            source: issues.redhat.com
          - id: RHOAIENG-32942
            source: issues.redhat.com
          - id: RHOAIENG-32922
            source: issues.redhat.com
          - id: RHOAIENG-32897
            source: issues.redhat.com
          - id: RHOAIENG-32847
            source: issues.redhat.com
          - id: RHOAIENG-32827
            source: issues.redhat.com
          - id: RHOAIENG-32826
            source: issues.redhat.com
          - id: RHOAIENG-32821
            source: issues.redhat.com
          - id: RHOAIENG-32666
            source: issues.redhat.com
          - id: RHOAIENG-32610
            source: issues.redhat.com
          - id: RHOAIENG-32588
            source: issues.redhat.com
          - id: RHOAIENG-32580
            source: issues.redhat.com
          - id: RHOAIENG-32533
            source: issues.redhat.com
          - id: RHOAIENG-32529
            source: issues.redhat.com
          - id: RHOAIENG-32528
            source: issues.redhat.com
          - id: RHOAIENG-32230
            source: issues.redhat.com
          - id: RHOAIENG-32222
            source: issues.redhat.com
          - id: RHOAIENG-31854
            source: issues.redhat.com
          - id: RHOAIENG-31839
            source: issues.redhat.com
          - id: RHOAIENG-31787
            source: issues.redhat.com
          - id: RHOAIENG-31785
            source: issues.redhat.com
          - id: RHOAIENG-31783
            source: issues.redhat.com
          - id: RHOAIENG-31782
            source: issues.redhat.com
          - id: RHOAIENG-31781
            source: issues.redhat.com
          - id: RHOAIENG-31779
            source: issues.redhat.com
          - id: RHOAIENG-31778
            source: issues.redhat.com
          - id: RHOAIENG-31777
            source: issues.redhat.com
          - id: RHOAIENG-31772
            source: issues.redhat.com
          - id: RHOAIENG-31771
            source: issues.redhat.com
          - id: RHOAIENG-31766
            source: issues.redhat.com
          - id: RHOAIENG-31765
            source: issues.redhat.com
          - id: RHOAIENG-31764
            source: issues.redhat.com
          - id: RHOAIENG-31763
            source: issues.redhat.com
          - id: RHOAIENG-31762
            source: issues.redhat.com
          - id: RHOAIENG-31761
            source: issues.redhat.com
          - id: RHOAIENG-31759
            source: issues.redhat.com
          - id: RHOAIENG-31758
            source: issues.redhat.com
          - id: RHOAIENG-31757
            source: issues.redhat.com
          - id: RHOAIENG-31756
            source: issues.redhat.com
          - id: RHOAIENG-31755
            source: issues.redhat.com
          - id: RHOAIENG-31754
            source: issues.redhat.com
          - id: RHOAIENG-31752
            source: issues.redhat.com
          - id: RHOAIENG-31751
            source: issues.redhat.com
          - id: RHOAIENG-31750
            source: issues.redhat.com
          - id: RHOAIENG-31749
            source: issues.redhat.com
          - id: RHOAIENG-31748
            source: issues.redhat.com
          - id: RHOAIENG-31747
            source: issues.redhat.com
          - id: RHOAIENG-31746
            source: issues.redhat.com
          - id: RHOAIENG-31745
            source: issues.redhat.com
          - id: RHOAIENG-31744
            source: issues.redhat.com
          - id: RHOAIENG-31743
            source: issues.redhat.com
          - id: RHOAIENG-31742
            source: issues.redhat.com
          - id: RHOAIENG-31741
            source: issues.redhat.com
          - id: RHOAIENG-31740
            source: issues.redhat.com
          - id: RHOAIENG-31739
            source: issues.redhat.com
          - id: RHOAIENG-31716
            source: issues.redhat.com
          - id: RHOAIENG-31714
            source: issues.redhat.com
          - id: RHOAIENG-31674
            source: issues.redhat.com
          - id: RHOAIENG-31673
            source: issues.redhat.com
          - id: RHOAIENG-31672
            source: issues.redhat.com
          - id: RHOAIENG-31671
            source: issues.redhat.com
          - id: RHOAIENG-31646
            source: issues.redhat.com
          - id: RHOAIENG-31618
            source: issues.redhat.com
          - id: RHOAIENG-31386
            source: issues.redhat.com
          - id: RHOAIENG-30493
            source: issues.redhat.com
          - id: RHOAIENG-30291
            source: issues.redhat.com
          - id: RHOAIENG-30231
            source: issues.redhat.com
          - id: RHOAIENG-29986
            source: issues.redhat.com
          - id: RHOAIENG-29716
            source: issues.redhat.com
          - id: RHOAIENG-28577
            source: issues.redhat.com
          - id: RHOAIENG-28576
            source: issues.redhat.com
          - id: RHOAIENG-28017
            source: issues.redhat.com
          - id: RHOAIENG-27684
            source: issues.redhat.com
          - id: RHOAIENG-26144
            source: issues.redhat.com
          - id: RHOAIENG-25586
            source: issues.redhat.com
          - id: RHOAIENG-24551
            source: issues.redhat.com
          - id: RHOAIENG-23751
            source: issues.redhat.com
          - id: RHOAIENG-22487
            source: issues.redhat.com
          - id: RHOAIENG-22448
            source: issues.redhat.com
          - id: RHOAIENG-13166
            source: issues.redhat.com
          - id: RHOAIENG-9418
            source: issues.redhat.com


