apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-5-ea-1-prod-1781711166
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 42edeba36844b5373317b11f2d88764b3706507b
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-5-ea-1
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-5-ea-1-components-prod
  snapshot: rhoai-v3-5-ea-1-1781222597
  data:
    version: 3.5.0-ea.1
    releaseNotes:
      type: RHSA
      issues:
        fixed:
          - id: RHOAIENG-66292
            source: issues.redhat.com
          - id: RHOAIENG-66108
            source: issues.redhat.com
          - id: RHOAIENG-65796
            source: issues.redhat.com
          - id: RHOAIENG-65423
            source: issues.redhat.com
          - id: RHOAIENG-65274
            source: issues.redhat.com
          - id: RHOAIENG-65189
            source: issues.redhat.com
          - id: RHOAIENG-64675
            source: issues.redhat.com
          - id: RHOAIENG-64674
            source: issues.redhat.com
          - id: RHOAIENG-64611
            source: issues.redhat.com
          - id: RHOAIENG-63704
            source: issues.redhat.com
          - id: RHOAIENG-63501
            source: issues.redhat.com
          - id: RHOAIENG-63500
            source: issues.redhat.com
          - id: RHOAIENG-63293
            source: issues.redhat.com
          - id: RHOAIENG-63291
            source: issues.redhat.com
          - id: RHOAIENG-62924
            source: issues.redhat.com
          - id: RHOAIENG-62673
            source: issues.redhat.com
          - id: RHOAIENG-62563
            source: issues.redhat.com
          - id: RHOAIENG-62532
            source: issues.redhat.com
          - id: RHOAIENG-62509
            source: issues.redhat.com
          - id: RHOAIENG-62502
            source: issues.redhat.com
          - id: RHOAIENG-62488
            source: issues.redhat.com
          - id: RHOAIENG-62354
            source: issues.redhat.com
          - id: RHOAIENG-62282
            source: issues.redhat.com
          - id: RHOAIENG-62269
            source: issues.redhat.com
          - id: RHOAIENG-62174
            source: issues.redhat.com
          - id: RHOAIENG-61960
            source: issues.redhat.com
          - id: RHOAIENG-61660
            source: issues.redhat.com
          - id: RHOAIENG-61646
            source: issues.redhat.com
          - id: RHOAIENG-61472
            source: issues.redhat.com
          - id: RHOAIENG-61470
            source: issues.redhat.com
          - id: RHOAIENG-61424
            source: issues.redhat.com
          - id: RHOAIENG-61277
            source: issues.redhat.com
          - id: RHOAIENG-61228
            source: issues.redhat.com
          - id: RHOAIENG-61227
            source: issues.redhat.com
          - id: RHOAIENG-61215
            source: issues.redhat.com
          - id: RHOAIENG-61208
            source: issues.redhat.com
          - id: RHOAIENG-61189
            source: issues.redhat.com
          - id: RHOAIENG-61185
            source: issues.redhat.com
          - id: RHOAIENG-61047
            source: issues.redhat.com
          - id: RHOAIENG-61028
            source: issues.redhat.com
          - id: RHOAIENG-61026
            source: issues.redhat.com
          - id: RHOAIENG-60940
            source: issues.redhat.com
          - id: RHOAIENG-60686
            source: issues.redhat.com
          - id: RHOAIENG-60685
            source: issues.redhat.com
          - id: RHOAIENG-60609
            source: issues.redhat.com
          - id: RHOAIENG-60550
            source: issues.redhat.com
          - id: RHOAIENG-60425
            source: issues.redhat.com
          - id: RHOAIENG-60419
            source: issues.redhat.com
          - id: RHOAIENG-60251
            source: issues.redhat.com
          - id: RHOAIENG-60220
            source: issues.redhat.com
          - id: RHOAIENG-60148
            source: issues.redhat.com
          - id: RHOAIENG-60145
            source: issues.redhat.com
          - id: RHOAIENG-59925
            source: issues.redhat.com
          - id: RHOAIENG-59861
            source: issues.redhat.com
          - id: RHOAIENG-59819
            source: issues.redhat.com
          - id: RHOAIENG-59759
            source: issues.redhat.com
          - id: RHOAIENG-59750
            source: issues.redhat.com
          - id: RHOAIENG-59731
            source: issues.redhat.com
          - id: RHOAIENG-59679
            source: issues.redhat.com
          - id: RHOAIENG-59657
            source: issues.redhat.com
          - id: RHOAIENG-59433
            source: issues.redhat.com
          - id: RHOAIENG-59403
            source: issues.redhat.com
          - id: RHOAIENG-59394
            source: issues.redhat.com
          - id: RHOAIENG-59192
            source: issues.redhat.com
          - id: RHOAIENG-59098
            source: issues.redhat.com
          - id: RHOAIENG-59097
            source: issues.redhat.com
          - id: RHOAIENG-59096
            source: issues.redhat.com
          - id: RHOAIENG-58853
            source: issues.redhat.com
          - id: RHOAIENG-58852
            source: issues.redhat.com
          - id: RHOAIENG-58851
            source: issues.redhat.com
          - id: RHOAIENG-58848
            source: issues.redhat.com
          - id: RHOAIENG-58760
            source: issues.redhat.com
          - id: RHOAIENG-58758
            source: issues.redhat.com
          - id: RHOAIENG-58730
            source: issues.redhat.com
          - id: RHOAIENG-58729
            source: issues.redhat.com
          - id: RHOAIENG-58719
            source: issues.redhat.com
          - id: RHOAIENG-58660
            source: issues.redhat.com
          - id: RHOAIENG-58617
            source: issues.redhat.com
          - id: RHOAIENG-58611
            source: issues.redhat.com
          - id: RHOAIENG-58577
            source: issues.redhat.com
          - id: RHOAIENG-58501
            source: issues.redhat.com
          - id: RHOAIENG-58473
            source: issues.redhat.com
          - id: RHOAIENG-58426
            source: issues.redhat.com
          - id: RHOAIENG-58422
            source: issues.redhat.com
          - id: RHOAIENG-58373
            source: issues.redhat.com
          - id: RHOAIENG-58263
            source: issues.redhat.com
          - id: RHOAIENG-57659
            source: issues.redhat.com
          - id: RHOAIENG-57645
            source: issues.redhat.com
          - id: RHOAIENG-57634
            source: issues.redhat.com
          - id: RHOAIENG-57633
            source: issues.redhat.com
          - id: RHOAIENG-57630
            source: issues.redhat.com
          - id: RHOAIENG-57629
            source: issues.redhat.com
          - id: RHOAIENG-57626
            source: issues.redhat.com
          - id: RHOAIENG-57095
            source: issues.redhat.com
          - id: RHOAIENG-56733
            source: issues.redhat.com
          - id: RHOAIENG-56558
            source: issues.redhat.com
          - id: RHOAIENG-56504
            source: issues.redhat.com
          - id: RHOAIENG-56285
            source: issues.redhat.com
          - id: RHOAIENG-56070
            source: issues.redhat.com
          - id: RHOAIENG-55623
            source: issues.redhat.com
          - id: RHOAIENG-54605
            source: issues.redhat.com
          - id: RHOAIENG-53341
            source: issues.redhat.com
          - id: RHOAIENG-52129
            source: issues.redhat.com
          - id: RHOAIENG-50523
            source: issues.redhat.com
          - id: RHOAIENG-50503
            source: issues.redhat.com
          - id: RHOAIENG-46780
            source: issues.redhat.com
          - id: RHOAIENG-37853
            source: issues.redhat.com
          - id: RHAIENG-5084
            source: issues.redhat.com
          - id: RHAIENG-5077
            source: issues.redhat.com
          - id: RHAIENG-5059
            source: issues.redhat.com
          - id: RHAIENG-5015
            source: issues.redhat.com
          - id: RHAIENG-5014
            source: issues.redhat.com
          - id: RHAIENG-5011
            source: issues.redhat.com
          - id: RHAIENG-5004
            source: issues.redhat.com
          - id: RHAIENG-5003
            source: issues.redhat.com
          - id: RHAIENG-4890
            source: issues.redhat.com
          - id: RHAIENG-4689
            source: issues.redhat.com
          - id: RHAIENG-4654
            source: issues.redhat.com
          - id: RHAIENG-3816
            source: issues.redhat.com
          - id: RHAIENG-3749
            source: issues.redhat.com
          - id: RHAIENG-1503
            source: issues.redhat.com
          - id: RHAIENG-394
            source: issues.redhat.com
      cves:
        - key: 'CVE-2025-61729'
          component: odh-feast-operator-v3-5-ea-1
