apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/actual-rbc-release-commit: a7144c25398336342101508a5817012fccf1dd21
    konflux-release-data/artifact-type: charts
    konflux-release-data/rbc-release-commit: 03881176af686ca5d06f50526dd774171a3ebdf5
    test.appstudio.openshift.io/type: override
  name: rhoai-v3-4-charts-1787265073
  namespace: rhoai-tenant
spec:
  application: rhoai-v3-4
  components:
  - containerImage: quay.io/rhoai/rhai-on-openshift-chart@sha256:37d90a062f2f1a1e0216af35450312b6719dada8eeca573bcd86e5ea36c5ef63
    name: rhai-on-openshift-chart-v3-4
  - containerImage: quay.io/rhoai/rhai-on-xks-chart@sha256:c6a35041d02184ab4c1a6b9eb8c139bfafcd4499a6b8fbaca222b2467d6b15aa
    name: rhai-on-xks-chart-v3-4
