apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-415-1759323414
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 1bc7dc5c1a6ef44291c2a823af48b15d783f84f2
    konflux-release-data/ocp-version: ocp-415
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-415
  components:
    - name: rhoai-fbc-fragment-ocp-415
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:36cd8ded59900d124a135b887deda8dc4106483a1aad625a852ae6493c4dc5b0
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 8ff5586572cc1a4ca88865b339feba9813456b97