apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: 8a9321d3c15146e7c0a23dd7ad6d6d2ddc2b464e
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-22-1752227882
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-22
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:b3abcd716f0ccb77acbb54b38b0d6aaccfa56626494a8d40895647803319af92
    name: odh-operator-bundle-v2-22
    source:
      git:
        revision: 73d1b3771903099e20475222f5937180cd6af0d8
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel9@sha256:582f7671f17a8f9fe3464f3442474dd9ef00d8da1c339bae7898139118f567a2
    name: odh-codeflare-operator-v2-22
    source:
      git:
        revision: c75b071686cd0055cad9a72dac32f2b3566fe77e
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel9@sha256:f0714e0f626bfec63cc3ae836618e2dab84f2e555e7c2d09d53fd8f6063e7863
    name: odh-dashboard-v2-22
    source:
      git:
        revision: a792da6994d4bb6bec4eed331727455e80c2b40c
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel9@sha256:debef4636b223a87194750f9f3cdbc1ff28da35159b22357e779820629a0554b
    name: odh-data-science-pipelines-argo-argoexec-v2-22
    source:
      git:
        revision: f35cfbedc5e07aac7410e0e07af647d7e2b6f92a
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9@sha256:3e46e0989d45a528c99ca15683a64bf0f3720cd9ac688535a696f4439a1ae213
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-22
    source:
      git:
        revision: f35cfbedc5e07aac7410e0e07af647d7e2b6f92a
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel9@sha256:06996ac2ef9386e4f1a779ce277ffd9e7a00ecd46298269ba669dc113ff3bf29
    name: odh-data-science-pipelines-operator-controller-v2-22
    source:
      git:
        revision: ae03e47ea30aa092424355116d78851ff84cbfab
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-feast-operator-rhel9@sha256:8f2ffcd7a15ac37f82be35743d9582814bd678859b5c5ce16ed91c5ea03a66ff
    name: odh-feast-operator-v2-22
    source:
      git:
        revision: f8bdd7a6b42d7751e44637b4dd99ae205d8ca0c2
        url: https://github.com/red-hat-data-services/feast
  - containerImage: quay.io/rhoai/odh-feature-server-rhel9@sha256:fc1ebfb8399f63f5936c7ff537941d4173cbc18a0b56a1a5e2bcb7d1ba8711f4
    name: odh-feature-server-v2-22
    source:
      git:
        revision: f8bdd7a6b42d7751e44637b4dd99ae205d8ca0c2
        url: https://github.com/red-hat-data-services/feast
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel9@sha256:a9284b66cf63b1f3ab35bdbfc401191220f48372d5b4d10a91250487cf5647f3
    name: odh-kf-notebook-controller-v2-22
    source:
      git:
        revision: 0bc78e3daa4609f3a4508e2adb4925fbbfc522e0
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel9@sha256:95b05d48cd7f2f4eb7f8589b36d9352ca4f309e227f5b9947d59590ade74e1bd
    name: odh-kuberay-operator-controller-v2-22
    source:
      git:
        revision: bfae29ef6ed60875c716431a108d933e6849ac5d
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel9@sha256:5195362289ea8ba5e0b0e07b1afbbf9204667a6ec58723f75b38ab86fa502406
    name: odh-kueue-controller-v2-22
    source:
      git:
        revision: 3d9ed4bd0de3ac36edfba5a9f1bbe1657883055c
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel9@sha256:228f93a4e9feef1a699829f906ef8cb9d56ac714abdc3a5692702b1b3a22995b
    name: odh-ml-pipelines-api-server-v2-v2-22
    source:
      git:
        revision: 49dc6318740575917b300df78975c728b821eeff
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel9@sha256:44d532c3c092c816212d54be478f3ea75743ed6dcb2679f3297b13194d009271
    name: odh-ml-pipelines-driver-v2-22
    source:
      git:
        revision: 49dc6318740575917b300df78975c728b821eeff
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel9@sha256:f04579809d03af3bcda94264d959244642829c7cc85dce2c7dd27edf395e3a1b
    name: odh-ml-pipelines-launcher-v2-22
    source:
      git:
        revision: 49dc6318740575917b300df78975c728b821eeff
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9@sha256:434b3897be1b657b62340ebdcad4c20dcd383ebf40fc48b9c385c0cfadc002dd
    name: odh-ml-pipelines-persistenceagent-v2-v2-22
    source:
      git:
        revision: 49dc6318740575917b300df78975c728b821eeff
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-runtime-generic-rhel9@sha256:6704ff9674557b2866822117f5986d497e35bd23bedb1a5507fafb394cd24e0f
    name: odh-ml-pipelines-runtime-generic-v2-22
    source:
      git:
        revision: cac10e0437438735d1e54f73e142d9e787a02307
        url: https://github.com/red-hat-data-services/ilab-on-ocp
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9@sha256:e07e88dcd4a77dac36c5fa9a4c6952b27e060bcf51fd2e516d2d44e2f2ec31db
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-22
    source:
      git:
        revision: 49dc6318740575917b300df78975c728b821eeff
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel9@sha256:767ba56a25b7617a4035b2cca7c1d53ac86eb0ad2928d82b3a9195fda31b6a55
    name: odh-mlmd-grpc-server-v2-22
    source:
      git:
        revision: 1dbf4dd373ce8a347a2e3227e41c6ee69034760f
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel9@sha256:4d012ab4e68f1cc3ca131cce93e749bfa7af1b9504624452a1dcca47254d55cf
    name: odh-mm-rest-proxy-v2-22
    source:
      git:
        revision: 07ca06fce1746aaa98541986100d5832fab1a539
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel9@sha256:6ec4325e1f5aa7db731eb6c698e9c7bfbce7b2ca96737b5a32faee3bd2c414f1
    name: odh-model-controller-v2-22
    source:
      git:
        revision: 5734d135631cdaad1b80f886b78f3d4dd137ac2c
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel9@sha256:f0c0f13fac0e859987e46a45a6a020a205dfa1e13dd6ed7987519f80eedb08a0
    name: odh-model-registry-operator-v2-22
    source:
      git:
        revision: e87bb3c9b485f7ce68d030a0bfecc9ec01b95ee1
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel9@sha256:d3268651cadbd7614b2a4730570fb5b444b0cfd20fc3487727c6fa65dbfbcdad
    name: odh-model-registry-v2-22
    source:
      git:
        revision: 2cd72a6b4db8206caaa018804cae223a619dbf76
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel9@sha256:addc88a6c0b38c673103fb3e827b5ff19484380fc0d06f73398c2fa165e725b4
    name: odh-modelmesh-v2-22
    source:
      git:
        revision: 19336f48233962cc30ae87f532ff20ed520a2ad7
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel9@sha256:6d6ee9cf65e4d474aea97f2fb1334ab617e1d9b8aba9d5fb9ee07cc0368e7526
    name: odh-modelmesh-runtime-adapter-v2-22
    source:
      git:
        revision: 56afd58346780f65b99118238e701a7c9893569a
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel9@sha256:ed9f85c7a4a087c1cae5b2f2e67e767d5beda3bf62a28656809f1b2e0d1c4296
    name: odh-modelmesh-serving-controller-v2-22
    source:
      git:
        revision: ec9473e9c8390b843bc1ca4ea7783319e39409ba
        url: https://github.com/red-hat-data-services/modelmesh-serving
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel9@sha256:0d66b92b3fd458678401587013518722aa36da563bb199ef89dc0ffb5f0121c4
    name: odh-notebook-controller-v2-22
    source:
      git:
        revision: 0bc78e3daa4609f3a4508e2adb4925fbbfc522e0
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel9-operator@sha256:d5dd8a71ba859f896c0fe066b2be97b179a7cc0f7e01144762a67fe52772785a
    name: odh-operator-v2-22
    source:
      git:
        revision: ef0f214b2a45fc74ecc8c1b60cb589f9353646c5
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel9@sha256:59984d62330d40dcf9415ac1ce00053ec8bb075682797815bdc4e7192705d6f3
    name: odh-training-operator-v2-22
    source:
      git:
        revision: 5b255173c551cb964f57d07ab8947518841e684c
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel9@sha256:09b1d9e21ee540410f0e7c7fd55741b0b7fb1ea42d2291aae0aaf6296214dc9f
    name: odh-trustyai-service-operator-v2-22
    source:
      git:
        revision: 683543e45b5355da32eee4bc8502da0698541aa1
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel9@sha256:28be7d527d46469b09fa0ac5b4a62f76bfb36d763d686cee949dbcd888ce9ab0
    name: odh-trustyai-service-v2-22
    source:
      git:
        revision: 4a1c51a68ea66c38d0bbc1ffe9d9434682f493ff
        url: https://github.com/red-hat-data-services/trustyai-explainability
