:apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-25-prod-1772640381-1
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 07c26f7439a298f8c2f78ccd584365daf5faf45f
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-25
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-components-prod
  snapshot: rhoai-v2-25-1772354515
  data:
    version: 2.25.3
    releaseNotes:
      cves:
        - key: 'CVE-2025-68121' # https://issues.redhat.com/browse/RHOAIENG-49744
          component: 'odh-rhel9-operator-v2-25'
        - key: 'CVE-2025-69227' # https://issues.redhat.com/browse/RHOAIENG-49627
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-69228' # https://issues.redhat.com/browse/RHOAIENG-49585
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-61726' # https://issues.redhat.com/browse/RHOAIENG-48587
          component: 'odh-codeflare-operator-v2-25'
        - key: 'CVE-2025-61726' # https://issues.redhat.com/browse/RHOAIENG-48535
          component: 'odh-rhel9-operator-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48361
          component: 'odh-vllm-rocm-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48360
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48359
          component: 'odh-vllm-cuda-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48358
          component: 'odh-vllm-cpu-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48357
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48356
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48355
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2026-22778' # https://issues.redhat.com/browse/RHOAIENG-48354
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-61728' # https://issues.redhat.com/browse/RHOAIENG-48165
          component: 'odh-modelmesh-serving-controller-v2-25'
        - key: 'CVE-2025-61728' # https://issues.redhat.com/browse/RHOAIENG-48162
          component: 'odh-model-controller-v2-25'
        - key: 'CVE-2026-24779' # https://issues.redhat.com/browse/RHOAIENG-47851
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2026-24779' # https://issues.redhat.com/browse/RHOAIENG-47848
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2026-24779' # https://issues.redhat.com/browse/RHOAIENG-47847
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2026-24779' # https://issues.redhat.com/browse/RHOAIENG-47846
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2026-24486' # https://issues.redhat.com/browse/RHOAIENG-47667
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2026-24486' # https://issues.redhat.com/browse/RHOAIENG-47663
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2026-24486' # https://issues.redhat.com/browse/RHOAIENG-47660
          component: 'odh-llama-stack-core-v2-25'
        - key: 'CVE-2025-13465' # https://issues.redhat.com/browse/RHOAIENG-47536
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2025-13465' # https://issues.redhat.com/browse/RHOAIENG-47535
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-47002
          component: 'odh-training-rocm62-torch25-py311-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-47001
          component: 'odh-training-rocm62-torch24-py311-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-47000
          component: 'odh-training-cuda124-torch25-py311-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-46999
          component: 'odh-training-cuda121-torch24-py311-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-46998
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2026-1260' # https://issues.redhat.com/browse/RHOAIENG-46997
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46974
          component: 'odh-training-rocm62-torch25-py311-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46973
          component: 'odh-training-rocm62-torch24-py311-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46972
          component: 'odh-training-cuda124-torch25-py311-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46971
          component: 'odh-training-cuda121-torch24-py311-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46962
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2026-24049' # https://issues.redhat.com/browse/RHOAIENG-46953
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2026-22807' # https://issues.redhat.com/browse/RHOAIENG-46794
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2026-22807' # https://issues.redhat.com/browse/RHOAIENG-46791
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2026-23745' # https://issues.redhat.com/browse/RHOAIENG-46376
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45803
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45802
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45801
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45800
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45799
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2026-0897' # https://issues.redhat.com/browse/RHOAIENG-45798
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-59057' # https://issues.redhat.com/browse/RHOAIENG-45127
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2025-59057' # https://issues.redhat.com/browse/RHOAIENG-45126
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2026-21884' # https://issues.redhat.com/browse/RHOAIENG-45121
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2026-21884' # https://issues.redhat.com/browse/RHOAIENG-45120
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2026-22029' # https://issues.redhat.com/browse/RHOAIENG-45101
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2026-22029' # https://issues.redhat.com/browse/RHOAIENG-45100
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2026-21441' # https://issues.redhat.com/browse/RHOAIENG-45050
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2026-21441' # https://issues.redhat.com/browse/RHOAIENG-44966
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2026-21441' # https://issues.redhat.com/browse/RHOAIENG-44952
          component: 'odh-dashboard-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44773
          component: 'odh-modelmesh-serving-controller-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44772
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44767
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44765
          component: 'odh-ml-pipelines-scheduledworkflow-v2-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44764
          component: 'odh-ml-pipelines-persistenceagent-v2-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44763
          component: 'odh-ml-pipelines-launcher-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44762
          component: 'odh-ml-pipelines-driver-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44761
          component: 'odh-ml-pipelines-api-server-v2-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44756
          component: 'odh-kuberay-operator-controller-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44753
          component: 'odh-data-science-pipelines-operator-controller-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44752
          component: 'odh-data-science-pipelines-argo-workflowcontroller-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44751
          component: 'odh-data-science-pipelines-argo-argoexec-v2-25'
        - key: 'CVE-2025-61729' # https://issues.redhat.com/browse/RHOAIENG-44750
          component: 'odh-codeflare-operator-v2-25'
        - key: 'CVE-2025-66471' # https://issues.redhat.com/browse/RHOAIENG-44328
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-66471' # https://issues.redhat.com/browse/RHOAIENG-44300
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-69223' # https://issues.redhat.com/browse/RHOAIENG-43597
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14930' # https://issues.redhat.com/browse/RHOAIENG-42989
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14930' # https://issues.redhat.com/browse/RHOAIENG-42982
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14929' # https://issues.redhat.com/browse/RHOAIENG-42946
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14929' # https://issues.redhat.com/browse/RHOAIENG-42939
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14928' # https://issues.redhat.com/browse/RHOAIENG-42909
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-14928' # https://issues.redhat.com/browse/RHOAIENG-42903
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14928' # https://issues.redhat.com/browse/RHOAIENG-42896
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14927' # https://issues.redhat.com/browse/RHOAIENG-42866
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-14927' # https://issues.redhat.com/browse/RHOAIENG-42860
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14927' # https://issues.redhat.com/browse/RHOAIENG-42853
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14926' # https://issues.redhat.com/browse/RHOAIENG-42817
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14926' # https://issues.redhat.com/browse/RHOAIENG-42810
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14924' # https://issues.redhat.com/browse/RHOAIENG-42767
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14921' # https://issues.redhat.com/browse/RHOAIENG-42738
          component: 'odh-vllm-rocm-v2-25'
        - key: 'CVE-2025-14921' # https://issues.redhat.com/browse/RHOAIENG-42737
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-14921' # https://issues.redhat.com/browse/RHOAIENG-42731
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14921' # https://issues.redhat.com/browse/RHOAIENG-42724
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14920' # https://issues.redhat.com/browse/RHOAIENG-42694
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-14920' # https://issues.redhat.com/browse/RHOAIENG-42688
          component: 'odh-openvino-model-server-v2-25'
        - key: 'CVE-2025-14920' # https://issues.redhat.com/browse/RHOAIENG-42681
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-14925' # https://issues.redhat.com/browse/RHOAIENG-42649
          component: 'odh-vllm-rocm-v2-25'
        - key: 'CVE-2025-14925' # https://issues.redhat.com/browse/RHOAIENG-42648
          component: 'odh-vllm-cuda-v2-25'
        - key: 'CVE-2025-14925' # https://issues.redhat.com/browse/RHOAIENG-42638
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-66418' # https://issues.redhat.com/browse/RHOAIENG-42048
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-66448' # https://issues.redhat.com/browse/RHOAIENG-41417
          component: 'odh-vllm-cpu-v2-25'
        - key: 'CVE-2025-59425' # https://issues.redhat.com/browse/RHOAIENG-41381
          component: 'odh-vllm-cpu-v2-25'
        - key: 'CVE-2025-12805' # https://issues.redhat.com/browse/RHOAIENG-38782
          component: 'odh-mod-arch-model-registry-v2-25'
        - key: 'CVE-2025-12805' # https://issues.redhat.com/browse/RHOAIENG-38780
          component: 'odh-dashboard-v2-25'
      issues:
          fixed:
            - id: RHOAIENG-47411
              source: issues.redhat.com
            - id: RHOAIENG-46747
              source: issues.redhat.com
            - id: RHOAIENG-41284
              source: issues.redhat.com
            - id: RHOAIENG-49899
              source: issues.redhat.com
