apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/actual-rbc-release-commit: 668ca47f63415a4e90c46bb1b9e23b41b98a5519
    konflux-release-data/artifact-type: charts
    konflux-release-data/rbc-release-commit: aa48a24d378d81007593abd9823d41adb4943032
    test.appstudio.openshift.io/type: override
  name: rhoai-v3-5-charts-1789884845
  namespace: rhoai-tenant
spec:
  application: rhoai-v3-5
  components:
  - containerImage: quay.io/rhoai/rhai-on-openshift-chart@sha256:1fdb9839192883c9f36717d2301009fa86cb0c97ea28d9203ea24d5c9fe33943
    name: rhai-on-openshift-chart-v3-5
  - containerImage: quay.io/rhoai/rhai-on-xks-chart@sha256:5e9a0c3df534f8a489cadb711b33d65516823c32b86fda8e9098ccb299ea531e
    name: rhai-on-xks-chart-v3-5
