{{- if .Values.coreweave.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.coreweave.cloudManager.namespace }}
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
