apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-16-prod-1774361234
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: f297576ca966f40e1b048caeeec041516395e1d8
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-16
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-16-components-prod
  snapshot: rhoai-v2-16-1774319602
  data:
    version: 2.16.4
    releaseNotes:
      cves:
        - key: 'CVE-2026-29074' # https://redhat.atlassian.net/browse/RHOAIENG-53349
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-32141' # https://redhat.atlassian.net/browse/RHOAIENG-53202
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-1526' # https://redhat.atlassian.net/browse/RHOAIENG-53035
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-2229' # https://redhat.atlassian.net/browse/RHOAIENG-53019
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-1528' # https://redhat.atlassian.net/browse/RHOAIENG-53017
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2025-69873' # https://redhat.atlassian.net/browse/RHOAIENG-49691
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-25639' # https://redhat.atlassian.net/browse/RHOAIENG-49361
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2026-25223' # https://redhat.atlassian.net/browse/RHOAIENG-48639
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2025-61726' # https://redhat.atlassian.net/browse/RHOAIENG-48562
          component: 'odh-notebook-controller-v2-16'
        - key: 'CVE-2025-61726' # https://redhat.atlassian.net/browse/RHOAIENG-48549
          component: 'odh-kuberay-operator-controller-v2-16'
        - key: 'CVE-2025-61726' # https://redhat.atlassian.net/browse/RHOAIENG-48548
          component: 'odh-kf-notebook-controller-v2-16'
        - key: 'CVE-2025-61726' # https://redhat.atlassian.net/browse/RHOAIENG-48544
          component: 'odh-codeflare-operator-v2-16'
        - key: 'CVE-2025-61729' # https://redhat.atlassian.net/browse/RHOAIENG-44702
          component: 'odh-notebook-controller-v2-16'
        - key: 'CVE-2025-61729' # https://redhat.atlassian.net/browse/RHOAIENG-44688
          component: 'odh-kf-notebook-controller-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42270
          component: 'odh-ml-pipelines-scheduledworkflow-v2-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42269
          component: 'odh-ml-pipelines-persistenceagent-v2-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42268
          component: 'odh-ml-pipelines-launcher-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42267
          component: 'odh-ml-pipelines-driver-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42266
          component: 'odh-ml-pipelines-api-server-v2-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42265
          component: 'odh-data-science-pipelines-argo-workflowcontroller-v2-16'
        - key: 'CVE-2025-68156' # https://redhat.atlassian.net/browse/RHOAIENG-42264
          component: 'odh-data-science-pipelines-argo-argoexec-v2-16'
        - key: 'CVE-2025-66418' # https://redhat.atlassian.net/browse/RHOAIENG-42031
          component: 'odh-modelmesh-runtime-adapter-v2-16'
        - key: 'CVE-2025-12816' # https://redhat.atlassian.net/browse/RHOAIENG-41770
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2025-66626' # https://redhat.atlassian.net/browse/RHOAIENG-41707
          component: 'odh-data-science-pipelines-argo-workflowcontroller-v2-16'
        - key: 'CVE-2025-66626' # https://redhat.atlassian.net/browse/RHOAIENG-41706
          component: 'odh-data-science-pipelines-argo-argoexec-v2-16'
        - key: 'CVE-2024-25621' # https://redhat.atlassian.net/browse/RHOAIENG-41430
          component: 'odh-model-controller-v2-16'
        - key: 'CVE-2025-66031' # https://redhat.atlassian.net/browse/RHOAIENG-41174
          component: 'odh-dashboard-v2-16'
        - key: 'CVE-2025-12638' # https://redhat.atlassian.net/browse/RHOAIENG-41170
          component: 'odh-modelmesh-runtime-adapter-v2-16'
        - key: 'CVE-2025-12060' # https://redhat.atlassian.net/browse/RHOAIENG-37900
          component: 'odh-modelmesh-runtime-adapter-v2-16'
        - key: 'CVE-2025-6193' # https://redhat.atlassian.net/browse/RHOAIENG-27840
          component: 'odh-trustyai-service-operator-v2-16'
      issues:
        fixed:
          - id: RHOAIENG-53349
            source: redhat.atlassian.net
          - id: RHOAIENG-53253
            source: redhat.atlassian.net
          - id: RHOAIENG-53202
            source: redhat.atlassian.net
          - id: RHOAIENG-53035
            source: redhat.atlassian.net
          - id: RHOAIENG-53019
            source: redhat.atlassian.net
          - id: RHOAIENG-53017
            source: redhat.atlassian.net
          - id: RHOAIENG-49691
            source: redhat.atlassian.net
          - id: RHOAIENG-49361
            source: redhat.atlassian.net
          - id: RHOAIENG-48639
            source: redhat.atlassian.net
          - id: RHOAIENG-48562
            source: redhat.atlassian.net
          - id: RHOAIENG-48549
            source: redhat.atlassian.net
          - id: RHOAIENG-48548
            source: redhat.atlassian.net
          - id: RHOAIENG-48544
            source: redhat.atlassian.net
          - id: RHOAIENG-48080
            source: redhat.atlassian.net
          - id: RHOAIENG-44702
            source: redhat.atlassian.net
          - id: RHOAIENG-44688
            source: redhat.atlassian.net
          - id: RHOAIENG-42270
            source: redhat.atlassian.net
          - id: RHOAIENG-42269
            source: redhat.atlassian.net
          - id: RHOAIENG-42268
            source: redhat.atlassian.net
          - id: RHOAIENG-42267
            source: redhat.atlassian.net
          - id: RHOAIENG-42266
            source: redhat.atlassian.net
          - id: RHOAIENG-42265
            source: redhat.atlassian.net
          - id: RHOAIENG-42264
            source: redhat.atlassian.net
          - id: RHOAIENG-42031
            source: redhat.atlassian.net
          - id: RHOAIENG-41770
            source: redhat.atlassian.net
          - id: RHOAIENG-41707
            source: redhat.atlassian.net
          - id: RHOAIENG-41706
            source: redhat.atlassian.net
          - id: RHOAIENG-41430
            source: redhat.atlassian.net
          - id: RHOAIENG-41174
            source: redhat.atlassian.net
          - id: RHOAIENG-41170
            source: redhat.atlassian.net
          - id: RHOAIENG-37900
            source: redhat.atlassian.net
          - id: RHOAIENG-34879
            source: redhat.atlassian.net
          - id: RHOAIENG-31065
            source: redhat.atlassian.net
          - id: RHOAIENG-27840
            source: redhat.atlassian.net
          - id: RHOAIENG-24477
            source: redhat.atlassian.net
