apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1790697234
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 6698aebba79bf61a3e101b04e9daa04717834284
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:4237ccb3f0530f95d2f9b80950db0d1cee8461847a1f5c8c1369e7ba8fc841ff
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 13eda09a4319b6641a987072b624212bfb72103f