apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1789136319
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 1d8312adfc50fc6fcf6643416ca35c483099581e
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:e9ab7f2e5ee0398ed4e4abb3394887aa3aa2a64d6722ce93926dc749b887ea10
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 302c1cad6fa852260d635f61c48a679754e46773