apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-19-prod-1758875170
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: d0f0d173f2b4e693d25dc21e1f46fc09d0169bc0
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-19
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-19-components-prod
  snapshot: rhoai-v2-19-1758819191
  data:
    version: 2.19.3
