apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1787313787
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 03881176af686ca5d06f50526dd774171a3ebdf5
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:0d5646f34ff0f3b67e05b78a01209561e90b5aae2933d7050a6f21af96300ceb
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: b807c13aad3199c76ccecda1cb2349edb2347bfc