apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-417-1781005297
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9628df633f53621ba4a485ea06f379a763c8c8d6
    konflux-release-data/ocp-version: ocp-417
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-417
  components:
    - name: rhoai-fbc-fragment-ocp-417
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:598e398e2a852ffbe21fd6cdb8acaaeadedac3b33e262b00b99bd241d01d17af
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 219902bcb43c310ebb10d688b8079d77937b3b6a