apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1781005297
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9628df633f53621ba4a485ea06f379a763c8c8d6
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:a89c9e3c68f8bbf1e9b0ef8c52e3d227c2842cf756ae16c90852f18c0196eea0
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 219902bcb43c310ebb10d688b8079d77937b3b6a