apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-416-1781005297
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9628df633f53621ba4a485ea06f379a763c8c8d6
    konflux-release-data/ocp-version: ocp-416
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-416
  components:
    - name: rhoai-fbc-fragment-ocp-416
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:88bc37ea890e4cf3af04b135611a12ff6becd15dd37cc0b906d9c321eb1ce059
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 219902bcb43c310ebb10d688b8079d77937b3b6a