apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-418-1781005297
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9628df633f53621ba4a485ea06f379a763c8c8d6
    konflux-release-data/ocp-version: ocp-418
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-418
  components:
    - name: rhoai-fbc-fragment-ocp-418
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:19a45ef6b200e7795ac22ab7bd7903bf9d72cfe25e885e17b4611ea6f4e948d6
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 219902bcb43c310ebb10d688b8079d77937b3b6a