apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1781005297
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9628df633f53621ba4a485ea06f379a763c8c8d6
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:0b3102c96aa4807186291d08b0cb5ef2e1f0ece0c4ff5d75142efa8a6a8baf1c
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 219902bcb43c310ebb10d688b8079d77937b3b6a