apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-v3-4
    konflux-release-data/actual-rbc-release-commit: bb961993d3ed55264b26390607f3898e5c9f8133
    konflux-release-data/artifact-type: charts
    konflux-release-data/environment: stage
    konflux-release-data/rbc-release-commit: 62ff0a2e146c344830dbcb06c2840f98bff4da9e
  name: rhoai-v3-4-charts-stage-1782834884
  namespace: rhoai-tenant
spec:
  data:
    version: 3.4.2
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-charts-stage
  snapshot: rhoai-v3-4-charts-1782834884
