apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-18-prod-1741640035
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 563ae1ab845f1f60381b146bebba457b68a4ea34
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-18-components-prod
  snapshot: rhoai-v2-18-1741027090
  data:
    releaseNotes:
      cves:
        - key: CVE-2024-11187 # https://issues.redhat.com/browse/RHOAIENG-20632
          component: odh-training-operator-v2-18
        - key: CVE-2025-24970 # https://issues.redhat.com/browse/RHOAIENG-20044
          component: odh-modelmesh-v2-18
        - key: CVE-2024-45338 # https://issues.redhat.com/browse/RHOAIENG-20043
          component: odh-modelmesh-runtime-adapter-v2-18
        - key: CVE-2024-45337 # https://issues.redhat.com/browse/RHOAIENG-20043
          component: odh-modelmesh-runtime-adapter-v2-18
        - key: CVE-2025-22150 # https://issues.redhat.com/browse/RHOAIENG-18494
          component: odh-dashboard-v2-18
        - key: CVE-2024-45338 # https://issues.redhat.com/browse/RHOAIENG-18403
          component: odh-mm-rest-proxy-v2-18

