apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-v3-3
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: stage
    konflux-release-data/rbc-release-commit: bcf0c204331a152d220dedec61ec73765eb6f8da
  name: rhoai-v3-3-stage-1779210391-1
  namespace: rhoai-tenant
spec:
  data:
    version: 3.3.3
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-3-components-stage
  snapshot: rhoai-v3-3-1779210391
