apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-414-1732645487
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: rhoai-fbc-fragment-ocp-414
  components:
    - name: rhoai-fbc-fragment-ocp-414
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:fc6b162ce335b23b2da1378d4d73781fb05e09899f31cd110a005f66ec45b757
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 99ebfa2980d0438af3efe7cf30e7c4ff7c6d87d6