apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-413-1732645487
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: rhoai-fbc-fragment-ocp-413
  components:
    - name: rhoai-fbc-fragment-ocp-413
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:515718b910d51b4fb9e0791ffd82cdb0b3a4d884690caad6b1dd2a9fd9ae3ff5
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 99ebfa2980d0438af3efe7cf30e7c4ff7c6d87d6