apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: df9b0cba5fcc93701a1b29d1cecbf8a0ad76a56c
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-19-1752085608
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-19
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:84d21a75f64dbb4a69ca5345d75a91ac9cf229d05a76dcdb1c349374e4b80d2d
    name: odh-operator-bundle-v2-19
    source:
      git:
        revision: 5dd95a4831b5a7e5269ec4a901a7f381b915db42
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel8@sha256:baefbe4e7dd5aa74c71cb81da4a7a2b888a02d3eb1398ec4419bd8003b77f0c2
    name: odh-codeflare-operator-v2-19
    source:
      git:
        revision: e853fb2b7e48384a73227a48f77ba2de09f7c7e3
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel8@sha256:af4e4119e8b33007f2a9595eb9e3134f1b766c3d0307edd297a35634c56c9930
    name: odh-dashboard-v2-19
    source:
      git:
        revision: 86d9913b28840b2f3606310b607ac6a4f40d8108
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel8@sha256:d24e277f468b0a48f38801e8e0bcfeb8264c3f7c128073ddaa17934b8572cc3c
    name: odh-data-science-pipelines-argo-argoexec-v2-19
    source:
      git:
        revision: 64c3e30e189c2a8d31257019ef36156330a1026e
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8@sha256:876ca7ce7b0b975688fb4a77d6cd1a6f87cf9eb40c2a9a5b84d8cffdc80eeebd
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-19
    source:
      git:
        revision: 64c3e30e189c2a8d31257019ef36156330a1026e
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel8@sha256:6275a19ef06114b33d79833a94ef10cc8203368eee98e5d415e73d20cae1db85
    name: odh-data-science-pipelines-operator-controller-v2-19
    source:
      git:
        revision: 8d8c2cc9992c50d345e4794a4062b1cba213b905
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel8@sha256:f49483df1d342d8e39f9a8085920aad79313a475df02a2292a136ecb784402b5
    name: odh-kf-notebook-controller-v2-19
    source:
      git:
        revision: f9c96aec604f5ecdbdd1053ebcdcf14cfc4f18a9
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel8@sha256:4e8f6c6ca0ed516b8310af0332637683b5bfc8f2946eb935c647698dffbbcc79
    name: odh-kuberay-operator-controller-v2-19
    source:
      git:
        revision: 296187c3c5cbefcb4307b255295fb46a170ef62a
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel8@sha256:b20ee16b776871d7c49b23f2bc91726812998561129f5dbd14eddbfe57964c93
    name: odh-kueue-controller-v2-19
    source:
      git:
        revision: 26395acfb4bca57fc5fbe3073db51de3060d68fc
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel8@sha256:71cd15f0b1acba3a48ebedff037bf8a846b426c18363a4de8896a376b6b7b3d5
    name: odh-ml-pipelines-api-server-v2-v2-19
    source:
      git:
        revision: 2198924dda29e855b7f57edf00e6afa621f8f05a
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel8@sha256:87685c5cab105d876ff0d14b0e24d8dc2a1ff5b55bebe36028c5f3376b2a5271
    name: odh-ml-pipelines-driver-v2-19
    source:
      git:
        revision: 2198924dda29e855b7f57edf00e6afa621f8f05a
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel8@sha256:bf6231bfdbe52b597d86e03e4730ec105ebe7a639fcd529268b7c0423f2a890c
    name: odh-ml-pipelines-launcher-v2-19
    source:
      git:
        revision: 2198924dda29e855b7f57edf00e6afa621f8f05a
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8@sha256:6ad35cf5c4c62ed5ad4e192afe8cebead9796cb24a964401c76ff8656c47742f
    name: odh-ml-pipelines-persistenceagent-v2-v2-19
    source:
      git:
        revision: 2198924dda29e855b7f57edf00e6afa621f8f05a
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-runtime-generic-rhel8@sha256:6166f525948a018c41d735014d97fdfa52024f7be31e18976d85d1a0d88901a0
    name: odh-ml-pipelines-runtime-generic-v2-19
    source:
      git:
        revision: e198668481fc241119f329982c1d24cee79fe95b
        url: https://github.com/red-hat-data-services/ilab-on-ocp
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8@sha256:49c02285fcef6949892cecca20eeee49d03a9bb4d17bb9ceff7c7a0dbbb8ab40
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-19
    source:
      git:
        revision: 2198924dda29e855b7f57edf00e6afa621f8f05a
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:bbef4839f24facce111d21aca43898dcf4e6cf57adb16200e3f1590bd5f89eae
    name: odh-mlmd-grpc-server-v2-19
    source:
      git:
        revision: 83a44807a191367d128b596b193d1ee595b95bc1
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel8@sha256:c1c97b6beb759d3f6f2dd53c4258e4ccbb3bf35cf11873bd446b135defaa69d6
    name: odh-mm-rest-proxy-v2-19
    source:
      git:
        revision: d101c8fedc2fae23b67efd1449e075c796ecd339
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel8@sha256:b6039c3c33a5dc345ceb8e757437bb13023d2bf85cc2b4c10b9ab3887e78e0c0
    name: odh-model-controller-v2-19
    source:
      git:
        revision: 0e7241f9a1c5a3b4e745fca2133d9a360d41f41d
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel8@sha256:b24c25dfdcefb4ec26e7f311c00798df108f7685def2b1762b7624fdfb160ebf
    name: odh-model-registry-operator-v2-19
    source:
      git:
        revision: 5c6cacd7b05d631389d36df985b769ef8180b998
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel8@sha256:520ed21b80e5487b3a0a13b7e5c7d791d4dd28e0b6799d57abb65d53fca5a03f
    name: odh-model-registry-v2-19
    source:
      git:
        revision: 3c35f3b583c86c62f0b4f9c008be9b444bab9e26
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel8@sha256:04ae1e75d0941b643ad9efd47ad299e55dd89079c1e00b69313e3c4033a5a127
    name: odh-modelmesh-v2-19
    source:
      git:
        revision: 7579b40d8d1977a53eaed5a6b5144371d9f2036d
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:6f01ac7cc62ab961b9c8a630a558338a61f6d7902301c4a1ad337495ac7ce85a
    name: odh-modelmesh-runtime-adapter-v2-19
    source:
      git:
        revision: da92ab72366d56232c789bb11c34efc53cddf317
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel8@sha256:de0e4b7fb822101198817e83cd7e9f4f7406e75ec91d07a833a27a417cffe66b
    name: odh-modelmesh-serving-controller-v2-19
    source:
      git:
        revision: e6475e7e4b2d3261d8b1641cb2f97d1379f7e660
        url: https://github.com/red-hat-data-services/modelmesh-serving
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel8@sha256:d47514cbceb3cc96e9d33b7db6fc1df60893e5c4118bf6086cdd27f04c472773
    name: odh-notebook-controller-v2-19
    source:
      git:
        revision: f9c96aec604f5ecdbdd1053ebcdcf14cfc4f18a9
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel8-operator@sha256:81538dd09286514e7fbf6c6dcd3ab7fa5674f7158eadee2710a3364722a6480d
    name: odh-operator-v2-19
    source:
      git:
        revision: 771309fdb6a7225677ecbf549e4b386b628a7356
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel8@sha256:4313cae03c041d461bc276abc23d706b582b5d16feab316796ca43478b9dc705
    name: odh-training-operator-v2-19
    source:
      git:
        revision: a6289b4c6615c6126226529de89c46b8eab1a2d2
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel8@sha256:c8c23c07038f59db848dea0d4247b62840dbe58e1c581dc0722fb9d7f9be3b75
    name: odh-trustyai-service-operator-v2-19
    source:
      git:
        revision: 10a20c2fa9eccc649a0cae2501cabd98d266a128
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel8@sha256:af4721d61dfb61c75488a1bd6a5f62b23e20d7b7586a9cf51ba062ece2837715
    name: odh-trustyai-service-v2-19
    source:
      git:
        revision: 5aecf99ecb5e6b02e703fe9b26292c213a3901bf
        url: https://github.com/red-hat-data-services/trustyai-explainability
