apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-415-prod-1752763517
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: eb6fa60b0dca29e8751e14fb8549405cc46f0e60
    konflux-release-data/ocp-version: ocp-415
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-415
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-22-ocp-415-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-415-1752604055
  data:
    version: 2.22.0
