apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-5-ea-2-charts-prod-1784117523
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 6f6f23fcb48b1981471ad14b8936b8397083adaf
    konflux-release-data/actual-rbc-release-commit: 92153aa34afe8fdddc742535b14ba261c43d8a7f
    konflux-release-data/artifact-type: charts
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-5-ea-2
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-5-ea-2-charts-prod
  snapshot: rhoai-v3-5-ea-2-charts-1784102908
  data:
    version: 3.5.0-ea.2
