apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-16-prod-1758874086
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 2daf1bcbf288d40e22ab19f865f3214c1d7affa2
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-16
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-16-components-prod
  snapshot: rhoai-v2-16-1758794212
  data:
    version: 2.16.3
