sbom-metadata:
  - env_vars:
      - "RELATED_IMAGE_RHAII_VLLM_CUDA_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_ROCM_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_SPYRE_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CPU_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_GAUDI_IMAGE"
    package: "vllm"
    suffix: "_UPSTREAM_VERSION"
