sbom-metadata:
  - env_vars:
      - "RELATED_IMAGE_RHAII_VLLM_CUDA_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CUDA_FAST_1_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CUDA_FAST_2_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_ROCM_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_ROCM_FAST_1_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_ROCM_FAST_2_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_SPYRE_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_SPYRE_FAST_1_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_SPYRE_FAST_2_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CPU_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CPU_FAST_1_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_CPU_FAST_2_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_GAUDI_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_GAUDI_FAST_1_IMAGE"
      - "RELATED_IMAGE_RHAII_VLLM_GAUDI_FAST_2_IMAGE"
    package: "vllm"
    suffix: "_UPSTREAM_VERSION"
