apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1778776387
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 0f855757d9c2429f5d6201c3d6104d514eb18629
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:042a88cc79c69352ce8962a9047453985fa5d42293d6f043dfac7a152cc6cf25
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: ea15393cb9095d09ebba7b833cec5697459c5878