apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1778776387
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 0f855757d9c2429f5d6201c3d6104d514eb18629
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:777b6dd3d582dbe40db7df1087948920689b4f4661eba68b4933bfcdf3033ead
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: ea15393cb9095d09ebba7b833cec5697459c5878