config:
  supported-ocp-versions:
    - version: v4.14
      discontinued-range: '>=2.21.1'

    - version: v4.15
      discontinued-range: '>=2.16.3'

    - version: v4.16
      discontinued-range: '>=3.0.0'

    - version: v4.17
      discontinued-range: '>=3.0.0'

    - version: v4.18
      discontinued-range: '>=3.0.0'

    - version: v4.19

    - version: v4.20
      onboarded-range: '>=2.25.0'

    - version: v4.21
      onboarded-range: '>=2.25.0 <2.26.0 || >=3.3.0'

    - version: v4.22
      onboarded-range: '>=2.25.0 <2.26.0 || >=3.4.0'
      skip-bundles:
        # https://redhat-internal.slack.com/archives/C08UHLCPLQ6/p1785343129026979?thread_ts=1785336075.692629&cid=C08UHLCPLQ6
        - rhods-operator.2.25.9
        - rhods-operator.2.25.10
