apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: 1b7a0f4614847305703561dc3831c6570f69299c
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-16-1774276268
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-16
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:1254d695e5c1282209ece2e7809d19a8dac5c8e9f9db78b6400661c22008097f
    name: odh-operator-bundle-v2-16
    source:
      git:
        revision: efac7ec34453bd1262b9a7fee6e216b18c528169
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel8@sha256:866cdb6854aa043a98f00f0f6ed1ff3d5fa917b15d083d58e42e40a0b6e7a7ea
    name: odh-codeflare-operator-v2-16
    source:
      git:
        revision: 1fcf245f1a02280b2b540e30e0f1be39a4bb6b11
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel8@sha256:8ad5be8346fb62eada87cbb54e6f925db4540f75392aa7b5ee5095a28c99b58c
    name: odh-dashboard-v2-16
    source:
      git:
        revision: b0fc0a69726ce4668257f69b6a170e84618c4404
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel8@sha256:0deaf80c9a2f2229048031d44d809ee1658b5bc654098660a05415bffdb918ee
    name: odh-data-science-pipelines-argo-argoexec-v2-16
    source:
      git:
        revision: 234849b6b07149c5b829d126756c37f7d184f3e7
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8@sha256:68f4cf32c255764a10157be7778e5dd701c56f752c6a5b77f840b724842e6803
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-16
    source:
      git:
        revision: 234849b6b07149c5b829d126756c37f7d184f3e7
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel8@sha256:bcfdb9a810837eb6ce7fe16bcbfb90023367980d9d16105f3d6ae70806eedb15
    name: odh-data-science-pipelines-operator-controller-v2-16
    source:
      git:
        revision: bd927f64be1e11817b5229108ea229a604943e6c
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel8@sha256:e3e1d8edea5741f341f588a4c4f3871000033397a20e8fd66613f92007b611ee
    name: odh-kf-notebook-controller-v2-16
    source:
      git:
        revision: aab5dbe7e06a601c5c5f613d2f84151fa88f4eb4
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel8@sha256:aad5959702521d2d20ec3aa4930753faacb2b4bce683ab242dcb2ccee76c5359
    name: odh-kuberay-operator-controller-v2-16
    source:
      git:
        revision: 54be75c6a61b2854e2eb28dcb4569dd6d89ce37c
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel8@sha256:fb1ad0c18707bd90c3cc15a933a8263754567daad48361b27b516197a6eacf0e
    name: odh-kueue-controller-v2-16
    source:
      git:
        revision: caff3f95e1cacae679adeed5ff38275269b86d94
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel8@sha256:949f3795ad287ec3f5e988c049eb505a86cd6221fc88582245c5bcee827e7661
    name: odh-ml-pipelines-api-server-v2-v2-16
    source:
      git:
        revision: 28b492c502151c7df4ea9a3653cb4eab1d7385f9
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel8@sha256:5928482a1d135b68c028b6336b52ad479d9b6ebb32aa0734ac1b65d856787151
    name: odh-ml-pipelines-driver-v2-16
    source:
      git:
        revision: 28b492c502151c7df4ea9a3653cb4eab1d7385f9
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel8@sha256:26b3febf24687db929ae1866b785ee8a046e549dade18bb38fe517c47635b6d4
    name: odh-ml-pipelines-launcher-v2-16
    source:
      git:
        revision: 28b492c502151c7df4ea9a3653cb4eab1d7385f9
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8@sha256:4b328d1440b461bd555b1153faaf324164451a3613d924f1dde4def8acc49c07
    name: odh-ml-pipelines-persistenceagent-v2-v2-16
    source:
      git:
        revision: 28b492c502151c7df4ea9a3653cb4eab1d7385f9
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8@sha256:d194162f8d1a7aec50572c0c4df3a8a30ffe38968868adf08750ea3440ac151e
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-16
    source:
      git:
        revision: 28b492c502151c7df4ea9a3653cb4eab1d7385f9
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:82eb230b482e796aac368eae726ebe5f1e2231e2c80e8047fff836972685ff40
    name: odh-mlmd-grpc-server-v2-16
    source:
      git:
        revision: fff30a2fa89b3051ca5f006db60f11d9c1e34f66
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel8@sha256:96aff8cfe85bdf44c7fd88fb2bee7da6c9ec83c178ec600a5ff0b3f8c5ee42c0
    name: odh-mm-rest-proxy-v2-16
    source:
      git:
        revision: adfa267a6c8d42d06f59c0c3886c4bb252601e28
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel8@sha256:55c6e634b8a3f91cc5696345ecf971f6cecacbe281ded8fbc35588960fa5321a
    name: odh-model-controller-v2-16
    source:
      git:
        revision: b26db6fe64ba513a67e066a30060c6efe5b28533
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel8@sha256:110962f341108a04a1a840e9250cef2996df54450a783f15f3a8ebe60e876bcd
    name: odh-model-registry-operator-v2-16
    source:
      git:
        revision: 00826f1c16e83cebb7b37d4c49300de841f52441
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel8@sha256:393fbc6e23c9aed72ac3f94422a85b493d98e885aac38d9be46a6c77f1a4eff3
    name: odh-model-registry-v2-16
    source:
      git:
        revision: 4d75a2bc39d023bbbd5399ad29b4b30c5fe15ef2
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel8@sha256:62451941c06377a9c1698e5f8b89fbccd2f597826bbf6b2469f437d55e833aee
    name: odh-modelmesh-v2-16
    source:
      git:
        revision: 436f3b7b6a512bc342b6b46c1f5a86d945fe73c6
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:b193271d87be611c01c02376fcda3e8788054201d589e008e98d04f81d07e815
    name: odh-modelmesh-runtime-adapter-v2-16
    source:
      git:
        revision: 7883174bdfc0e7e312b26bd4648c4ea75fa51c01
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel8@sha256:cf5da260792a9c6b92046ecaa86393d2b10aaee34efc4c59c5ca26fe45cddced
    name: odh-modelmesh-serving-controller-v2-16
    source:
      git:
        revision: 5c76f59bf24b61fb3392d3eadf1fb6fe28211034
        url: https://github.com/red-hat-data-services/modelmesh-serving
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel8@sha256:f38ab10c2046e750e1744297488533638d916429a49b2b29317baac01ba3abf7
    name: odh-notebook-controller-v2-16
    source:
      git:
        revision: aab5dbe7e06a601c5c5f613d2f84151fa88f4eb4
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel8-operator@sha256:b7307fc33c57b0daa6ffd35fddb4887cde48469fb8c7d3df9c193abb44750fd4
    name: odh-operator-v2-16
    source:
      git:
        revision: 279f36c9c876d00b1febd0055f642892ac56d244
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel8@sha256:ff2d0451044ba8cb0d5e90975294f639cb434ccf32999a3244032fc4c83f14bd
    name: odh-training-operator-v2-16
    source:
      git:
        revision: d7186960a1ffad0a6d19c105707d6c86d6453380
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel8@sha256:b116e6ad2a2bcafbe30cd269f2b83dc256206af1b9048afc921eb62692734e1a
    name: odh-trustyai-service-operator-v2-16
    source:
      git:
        revision: 9a7750d387a845b0bfd6ff596662704199de01c3
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel8@sha256:7a0c5234e72ac226cca653216ac727bcdd60ddbbd90c1137064c4fe23a4171c3
    name: odh-trustyai-service-v2-16
    source:
      git:
        revision: b4038e78ab57033cd62b9c009b01b3c08791a33b
        url: https://github.com/red-hat-data-services/trustyai-explainability
