{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhaiOperator.namespace }}
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
