apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-421-prod-1782294734
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 316a4ac67b941cdb3b4c7eae3b2e8cfbf8c85b0c
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-ocp-421-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-421-1782207110
  data:
    version: 2.25.8
