apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-5-ea-1-charts-prod-1781711166
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 42edeba36844b5373317b11f2d88764b3706507b
    konflux-release-data/actual-rbc-release-commit: bbaf72dd568be78ad4c908d6ecdc7c66c3e2a98b
    konflux-release-data/artifact-type: charts
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-5-ea-1
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-5-ea-1-charts-prod
  snapshot: rhoai-v3-5-ea-1-charts-1781268100
  data:
    version: 3.5.0-ea.1
