apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-0-prod-1762938758
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 95084eabda471f4033ffb2af294b2d84e0b5c3b3
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-0
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-0-components-prod
  snapshot: rhoai-v3-0-1762770161
  data:
    version: 3.0.0
    releaseNotes:
      cves:
        - key: 'CVE-2025-12103' # https://issues.redhat.com/browse/RHOAIENG-36992
          component: 'odh-trustyai-service-operator-v3-0'
