apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-416-1733161774
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: a1b6fc5a4106394181e1fe0ad0a3ea0d18b5b636
spec:
  application: rhoai-fbc-fragment-ocp-416
  components:
    - name: rhoai-fbc-fragment-ocp-416
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:312d8044f389e4ce6058bceaeae3477587a6579d993ec7c966e33133579dd72b
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: c7839c2cc557a80ec97e5cf316af476e08f9607a