apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-420-prod-1778733813
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: d06b242f2226e089f784327797279f4e1a3b778f
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-ocp-420-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-420-1778703663
  data:
    version: 3.4.0
