apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-421-prod-1782401081
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 3742fe0b679103d31dac4091cc2102273d6ff2f4
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-3-ocp-421-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-421-1782381920
  data:
    version: 3.3.4
