apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: rhoai-v2-25
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: stage
    konflux-release-data/rbc-release-commit: 07c26f7439a298f8c2f78ccd584365daf5faf45f
  name: rhoai-v2-25-stage-1772354515
  namespace: rhoai-tenant
spec:
  data:
    version: 2.25.3
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-components-stage
  snapshot: rhoai-v2-25-1772354515
