apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1783108273
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 9e62817cf9ed15b3d1ca6fa3dd393670e7a0fecd
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:2a6ab7b5561f987bd0aed8e4dff70472cfd26708608654f7175066f65354c432
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: e1c7ed360034ad3ce0014667b03077b15c3fa397