apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-4-prod-1782919787-1
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 62ff0a2e146c344830dbcb06c2840f98bff4da9e
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-4
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-components-prod
  snapshot: rhoai-v3-4-1782829383
  data:
    version: 3.4.2
    releaseNotes:
      cves:
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66285
          component: 'odh-th06-rocm64-torch291-py312-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66281
          component: 'odh-training-rocm62-torch25-py311-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66280
          component: 'odh-training-rocm62-torch24-py311-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66277
          component: 'odh-training-cuda128-torch29-py312-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66276
          component: 'odh-training-cuda121-torch24-py311-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66275
          component: 'odh-training-cuda124-torch25-py311-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66266
          component: 'odh-th06-cpu-torch210-py312-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66265
          component: 'odh-training-rocm64-torch28-py312-v3-4'
        - key: 'CVE-2026-5241' # https://redhat.atlassian.net/browse/RHOAIENG-66264
          component: 'odh-th06-cuda130-torch210-py312-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66034
          component: 'odh-training-cuda124-torch25-py311-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66031
          component: 'odh-training-rocm64-torch28-py312-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66026
          component: 'odh-training-rocm62-torch24-py311-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66024
          component: 'odh-mlserver-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66020
          component: 'odh-training-cuda128-torch29-py312-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66015
          component: 'odh-training-rocm62-torch25-py311-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66013
          component: 'odh-training-cuda121-torch24-py311-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66011
          component: 'odh-trustyai-garak-lls-provider-dsp-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66009
          component: 'odh-training-rocm64-torch29-py312-v3-4'
        - key: 'CVE-2026-34993' # https://redhat.atlassian.net/browse/RHOAIENG-66007
          component: 'odh-training-cuda128-torch28-py312-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65876
          component: 'odh-mod-arch-maas-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65872
          component: 'odh-mod-arch-model-registry-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65871
          component: 'odh-mod-arch-eval-hub-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65868
          component: 'odh-mod-arch-gen-ai-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65866
          component: 'odh-mod-arch-automl-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65864
          component: 'odh-mod-arch-mlflow-v3-4'
        - key: 'CVE-2026-33245' # https://redhat.atlassian.net/browse/RHOAIENG-65863
          component: 'odh-mod-arch-autorag-v3-4'
        - key: 'CVE-2026-2614' # https://redhat.atlassian.net/browse/RHOAIENG-65834
          component: 'odh-th06-cpu-torch210-py312-v3-4'
        - key: 'CVE-2026-2614' # https://redhat.atlassian.net/browse/RHOAIENG-65831
          component: 'odh-training-cuda128-torch29-py312-v3-4'
        - key: 'CVE-2026-2614' # https://redhat.atlassian.net/browse/RHOAIENG-65824
          component: 'odh-th06-cuda130-torch210-py312-v3-4'
        - key: 'CVE-2026-2614' # https://redhat.atlassian.net/browse/RHOAIENG-65821
          component: 'odh-th06-rocm64-torch291-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64931
          component: 'odh-workbench-jupyter-trustyai-cpu-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64930
          component: 'odh-llama-stack-core-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64928
          component: 'odh-workbench-jupyter-pytorch-rocm-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64925
          component: 'odh-trustyai-garak-lls-provider-dsp-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64924
          component: 'odh-workbench-codeserver-datascience-cpu-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64922
          component: 'odh-pipeline-runtime-datascience-cpu-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64918
          component: 'odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64917
          component: 'odh-pipeline-runtime-pytorch-rocm-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64916
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64915
          component: 'odh-workbench-jupyter-datascience-cpu-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64914
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64911
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64910
          component: 'odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64909
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64905
          component: 'odh-workbench-jupyter-pytorch-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64903
          component: 'odh-pipeline-runtime-pytorch-cuda-py312-v3-4'
        - key: 'CVE-2026-48710' # https://redhat.atlassian.net/browse/RHOAIENG-64902
          component: 'odh-trustyai-nemo-guardrails-server-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64109
          component: 'odh-training-rocm62-torch24-py311-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64107
          component: 'odh-training-rocm64-torch29-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64106
          component: 'odh-training-cuda128-torch28-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64104
          component: 'odh-training-rocm64-torch28-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64102
          component: 'odh-training-cuda128-torch29-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64101
          component: 'odh-training-rocm62-torch25-py311-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64099
          component: 'odh-th06-cuda130-torch210-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64098
          component: 'odh-training-cuda121-torch24-py311-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64095
          component: 'odh-th06-cpu-torch291-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64093
          component: 'odh-th06-cpu-torch210-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64091
          component: 'odh-th06-cuda130-torch291-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64090
          component: 'odh-training-cuda124-torch25-py311-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64089
          component: 'odh-th06-rocm64-torch291-py312-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64083
          component: 'odh-kserve-storage-initializer-v3-4'
        - key: 'CVE-2026-8643' # https://redhat.atlassian.net/browse/RHOAIENG-64081
          component: 'odh-mlserver-v3-4'
      issues:
          fixed:
            - id: RHOAIENG-66285
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66281
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66280
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66277
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66276
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66275
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66266
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66265
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66264
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66034
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66031
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66026
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66024
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66020
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66015
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66013
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66011
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66009
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-66007
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65876
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65872
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65871
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65868
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65866
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65864
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65863
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65834
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65831
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65824
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65821
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64931
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64930
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64928
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64925
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64924
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64922
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64918
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64917
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64916
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64915
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64914
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64911
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64910
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64909
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64905
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64903
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64902
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64109
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64107
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64106
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64104
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64102
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64101
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64099
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64098
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64095
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64093
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64091
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64090
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64089
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64083
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64081
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-67549
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-65547
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64768
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-64437
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-63795
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-63792
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-63756
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-61112
              public: true
              source: redhat.atlassian.net
            - id: RHOAIENG-59726
              public: true
              source: redhat.atlassian.net
