apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1782917080
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 62ff0a2e146c344830dbcb06c2840f98bff4da9e
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:939f1152a61dc5469332083884715ee9fffd0f695be207047af53437067a4d5f
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: a27dd46960ea6b2b3b467f875e83d6fc8710b0e5