apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1788371199
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 54fbe38170a12b820d2c8c58724b21182ebd50dc
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:8f28e66b11dfab8b526c3f3770a2c43fa499a627e586b5efb8b16d4b5806575d
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 28381dfb60dc51842cbb4236fa6316f66001faa2