apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-417-1788371199
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 54fbe38170a12b820d2c8c58724b21182ebd50dc
    konflux-release-data/ocp-version: ocp-417
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-417
  components:
    - name: rhoai-fbc-fragment-ocp-417
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:29e54b5e886b395a89b936f6597c9c2e40ec4aa16734eb10aa73f6a043e6cb80
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 28381dfb60dc51842cbb4236fa6316f66001faa2