apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1788371199
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 54fbe38170a12b820d2c8c58724b21182ebd50dc
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:07e4c246ad86ac098ace6ead66b19f37fc7ffad079ee2def86ba0a42aa53947d
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 28381dfb60dc51842cbb4236fa6316f66001faa2