apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/actual-rbc-release-commit: bb961993d3ed55264b26390607f3898e5c9f8133
    konflux-release-data/artifact-type: charts
    konflux-release-data/rbc-release-commit: 62ff0a2e146c344830dbcb06c2840f98bff4da9e
    test.appstudio.openshift.io/type: override
  name: rhoai-v3-4-charts-1782834884
  namespace: rhoai-tenant
spec:
  application: rhoai-v3-4
  components:
  - containerImage: quay.io/rhoai/rhai-on-openshift-chart@sha256:5a164ed89e67619f6e7ced4ac1bdc9ae778f9649bbf0f81c9541374d6ddb4c72
    name: rhai-on-openshift-chart-v3-4
  - containerImage: quay.io/rhoai/rhai-on-xks-chart@sha256:fae51e2e355d3a32f4efa907c5ea33159a78e315d35abc792c76dd672dba1188
    name: rhai-on-xks-chart-v3-4
