apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1779221507
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: bcf0c204331a152d220dedec61ec73765eb6f8da
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:4c8af161009921f341682a5fdfdf05e30cfc84714f692c4a309cad7bb9c5f63d
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: fcaeb6251de571e1a1feca35f6092ae23711f54a