apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1779221507
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: bcf0c204331a152d220dedec61ec73765eb6f8da
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:2e7964a48e7f78b5dfd6e8cb3052f0f76b2a6c9c8efb562f2677d6ff495a97de
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: fcaeb6251de571e1a1feca35f6092ae23711f54a