apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-25-prod-1765976831
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: deaaea1441c3fb251880ac83ca714d7391e91d55
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-25
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-components-prod
  snapshot: rhoai-v2-25-1765815284
  data:
    version: 2.25.1
    releaseNotes:
      cves:
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41188
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41187
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41185
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41183
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41181
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41179
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41177
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41175
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-12638' # https://issues.redhat.com/browse/RHOAIENG-41173
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41161
          component: 'odh-ta-lmes-job-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41159
          component: 'odh-workbench-jupyter-trustyai-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41157
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41155
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41153
          component: 'odh-workbench-jupyter-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41151
          component: 'odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41148
          component: 'odh-workbench-jupyter-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41145
          component: 'odh-workbench-jupyter-minimal-rocm-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41143
          component: 'odh-workbench-jupyter-minimal-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41141
          component: 'odh-workbench-jupyter-minimal-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41139
          component: 'odh-workbench-jupyter-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41137
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41135
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41133
          component: 'odh-pipeline-runtime-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41131
          component: 'odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41128
          component: 'odh-pipeline-runtime-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41126
          component: 'odh-pipeline-runtime-minimal-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41124
          component: 'odh-pipeline-runtime-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41122
          component: 'odh-workbench-codeserver-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41121
          component: 'odh-ml-pipelines-runtime-generic-v2-25'
        - key: 'CVE-2025-64756' # https://issues.redhat.com/browse/RHOAIENG-41117
          component: 'odh-feature-server-v2-25'
        - key: 'CVE-2025-66416' # https://issues.redhat.com/browse/RHOAIENG-41105
          component: 'odh-feature-server-v2-25'
        - key: 'CVE-2025-62593' # https://issues.redhat.com/browse/RHOAIENG-40486
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-62593' # https://issues.redhat.com/browse/RHOAIENG-40485
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-62593' # https://issues.redhat.com/browse/RHOAIENG-40484
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-62593' # https://issues.redhat.com/browse/RHOAIENG-40483
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-47913' # https://issues.redhat.com/browse/RHOAIENG-39703
          component: 'odh-data-science-pipelines-argo-workflowcontroller-v2-25'
        - key: 'CVE-2025-47913' # https://issues.redhat.com/browse/RHOAIENG-39702
          component: 'odh-data-science-pipelines-argo-argoexec-v2-25'
        - key: 'CVE-2025-62164' # https://issues.redhat.com/browse/RHOAIENG-39642
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-62164' # https://issues.redhat.com/browse/RHOAIENG-39640
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-62164' # https://issues.redhat.com/browse/RHOAIENG-39638
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-62164' # https://issues.redhat.com/browse/RHOAIENG-39636
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38862
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38861
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38860
          component: 'odh-workbench-jupyter-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38859
          component: 'odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38858
          component: 'odh-workbench-jupyter-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38857
          component: 'odh-workbench-jupyter-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38856
          component: 'odh-workbench-codeserver-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38855
          component: 'odh-vllm-rocm-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38854
          component: 'odh-vllm-gaudi-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38853
          component: 'odh-vllm-cuda-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38852
          component: 'odh-vllm-cpu-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38851
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38850
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38849
          component: 'odh-pipeline-runtime-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38848
          component: 'odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38847
          component: 'odh-pipeline-runtime-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38846
          component: 'odh-pipeline-runtime-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38845
          component: 'odh-llama-stack-core-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38844
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38843
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38842
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38841
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38840
          component: 'odh-guardrails-detector-huggingface-runtime-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38839
          component: 'odh-caikit-tgis-serving-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38838
          component: 'odh-caikit-nlp-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-38837
          component: 'odh-built-in-detector-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37912
          component: 'odh-workbench-jupyter-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37911
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37910
          component: 'odh-pipeline-runtime-tensorflow-rocm-py312-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37909
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37908
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37907
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37906
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37905
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-12060' # https://issues.redhat.com/browse/RHOAIENG-37904
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-58183' # https://issues.redhat.com/browse/RHOAIENG-37755
          component: 'odh-rhel9-operator-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-37727
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-62727' # https://issues.redhat.com/browse/RHOAIENG-37436
          component: 'odh-feature-server-v2-25'
        - key: 'CVE-2025-9906' # https://issues.redhat.com/browse/RHOAIENG-37382
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-9905' # https://issues.redhat.com/browse/RHOAIENG-37373
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36672
          component: 'odh-workbench-jupyter-trustyai-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36667
          component: 'odh-workbench-jupyter-trustyai-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36662
          component: 'odh-workbench-jupyter-tensorflow-rocm-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36657
          component: 'odh-workbench-jupyter-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36652
          component: 'odh-workbench-jupyter-tensorflow-cuda-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36647
          component: 'odh-workbench-jupyter-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36642
          component: 'odh-workbench-jupyter-pytorch-rocm-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36637
          component: 'odh-workbench-jupyter-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36632
          component: 'odh-workbench-jupyter-pytorch-cuda-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36627
          component: 'odh-workbench-jupyter-minimal-rocm-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36622
          component: 'odh-workbench-jupyter-minimal-rocm-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36617
          component: 'odh-workbench-jupyter-minimal-cuda-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36612
          component: 'odh-workbench-jupyter-minimal-cuda-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36607
          component: 'odh-workbench-jupyter-minimal-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36602
          component: 'odh-workbench-jupyter-minimal-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36597
          component: 'odh-workbench-jupyter-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36592
          component: 'odh-workbench-jupyter-datascience-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36587
          component: 'odh-workbench-codeserver-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36582
          component: 'odh-workbench-codeserver-datascience-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36577
          component: 'odh-pipeline-runtime-tensorflow-rocm-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36572
          component: 'odh-pipeline-runtime-tensorflow-cuda-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36567
          component: 'odh-pipeline-runtime-tensorflow-cuda-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36562
          component: 'odh-pipeline-runtime-pytorch-rocm-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36557
          component: 'odh-pipeline-runtime-pytorch-rocm-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36552
          component: 'odh-pipeline-runtime-pytorch-cuda-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36547
          component: 'odh-pipeline-runtime-pytorch-cuda-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36542
          component: 'odh-pipeline-runtime-minimal-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36537
          component: 'odh-pipeline-runtime-minimal-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36531
          component: 'odh-pipeline-runtime-datascience-cpu-py312-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36526
          component: 'odh-pipeline-runtime-datascience-cpu-py311-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36521
          component: 'odh-modelmesh-runtime-adapter-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36511
          component: 'odh-kserve-storage-initializer-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36506
          component: 'odh-kserve-router-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36501
          component: 'odh-kserve-controller-v2-25'
        - key: 'CVE-2025-49655' # https://issues.redhat.com/browse/RHOAIENG-36496
          component: 'odh-kserve-agent-v2-25'
        - key: 'CVE-2025-53643' # https://issues.redhat.com/browse/RHOAIENG-35252
          component: 'odh-feature-server-v2-25'
      issues:
          fixed:
          - id: RHOAIENG-41821
            source: issues.redhat.com
          - id: RHOAIENG-41762
            source: issues.redhat.com
          - id: RHOAIENG-39781
            source: issues.redhat.com
          - id: RHOAIENG-39030
            source: issues.redhat.com
          - id: RHOAIENG-38911
            source: issues.redhat.com
          - id: RHOAIENG-38834
            source: issues.redhat.com
          - id: RHOAIENG-37889
            source: issues.redhat.com
          - id: RHOAIENG-37732
            source: issues.redhat.com
          - id: RHOAIENG-37511
            source: issues.redhat.com
          - id: RHOAIENG-37391
            source: issues.redhat.com
          - id: RHOAIENG-33609
            source: issues.redhat.com
          - id: RHOAIENG-31669
            source: issues.redhat.com
          - id: RHAIENG-2344
            source: issues.redhat.com
          - id: RHAIENG-2318
            source: issues.redhat.com
          - id: RHAIENG-2302
            source: issues.redhat.com
          - id: RHAIENG-2040
            source: issues.redhat.com
          - id: RHAIENG-2037
            source: issues.redhat.com
          - id: RHAIENG-1512
            source: issues.redhat.com
