apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/actual-rbc-release-commit: 7b4908f8bdf5c6337488021d52c0ba132ddb6eb7
    konflux-release-data/artifact-type: charts
    konflux-release-data/rbc-release-commit: e2a5cb14463a313ebd727f7109ee65972274896b
    test.appstudio.openshift.io/type: override
  name: rhoai-v3-4-charts-1781689704
  namespace: rhoai-tenant
spec:
  application: rhoai-v3-4
  components:
  - containerImage: quay.io/rhoai/rhai-on-openshift-chart@sha256:13d90f3d76ac3fb81107812d282446e80cd7e35eb2c9a78dbc7acd702128f141
    name: rhai-on-openshift-chart-v3-4
  - containerImage: quay.io/rhoai/rhai-on-xks-chart@sha256:256f2a3cb35ca37ff0854df0e30c8227ddbb69ac7866951aa7aecb03731a5764
    name: rhai-on-xks-chart-v3-4
