apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1741044778
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 563ae1ab845f1f60381b146bebba457b68a4ea34
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:40348ca0eed86299fb4f7ea88be62b6ef6f38c9ce75ba7d329101cb77cebb08c
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: c200e59da8dbaa67ae7d4958a3658d5be7730a51