apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-418-1741044778
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 563ae1ab845f1f60381b146bebba457b68a4ea34
    konflux-release-data/ocp-version: ocp-418
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-418
  components:
    - name: rhoai-fbc-fragment-ocp-418
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:42f0190a44826ecbc9b4495ce0c9e1ce57979c023d05580f8ab9b292ca4b5cd1
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: c200e59da8dbaa67ae7d4958a3658d5be7730a51