apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-6-ea-1-charts-prod-1790187266
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 588ca86a37992f026dcce579f6f2611afc96fcb1
    konflux-release-data/actual-rbc-release-commit: 8d4a53372721605cbb369d4796bc8b7d1c1974a5
    konflux-release-data/artifact-type: charts
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-6-ea-1
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-6-ea-1-charts-prod
  snapshot: rhoai-v3-6-ea-1-charts-1789718548
  data:
    version: 3.6.0-ea.1
