apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/RHOAI-Build-Config?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "enum-test"
  labels:
    appstudio.openshift.io/application: rhoai-v2-20
    appstudio.openshift.io/component: rhoai-fbc-fragment-v2-20
    pipelines.appstudio.openshift.io/type: build
  name: rhoai-fbc-fragment-rhoai-30-ocp-419-on-push
  namespace: rhoai-tenant
spec:
  timeouts:
    pipeline: 8h
    tasks: 4h
  params:
  - name: build-type
    value: "stage"
  pipelineSpec:
    description: |
      This pipeline is ideal for building and verifying [file-based catalogs](https://konflux-ci.dev/docs/advanced-how-tos/building-olm.adoc#building-the-file-based-catalog).

      _Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and do not scan the image.
      This pipeline is pushed as a Tekton bundle to [quay.io](https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-fbc-builder?tab=tags)_
    
    params:
    - description: Build Type
      name: build-type
      enum: ["ci", "nightly", "stage"]
      default: "ci"
    tasks:
    - name: test
      params:
      - name: image-url
        value: $(params.output-image)
      - name: build-type
        value: $(params.build-type)
      taskSpec:
      steps:
      - name: noop
        image: quay.io/rhoai-konflux/alpine:latest
        script: |
          echo "Parameter value: $(params.build-type)"
    workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  taskRunTemplate: 
    serviceAccountName: build-pipeline-rhoai-fbc-fragment-v3-0
  workspaces:
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
