apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: rhoai-fbc-fragment-rhoai-30-ocp-419-on-push
  namespace: rhoai-tenant
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/RHOAI-Build-Config?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "enum-test"
  labels:
    appstudio.openshift.io/application: rhoai-v2-20
    appstudio.openshift.io/component: rhoai-fbc-fragment-v2-20
    pipelines.appstudio.io/type: build
spec:
  timeouts:
    pipeline: 8h
    tasks: 4h
  params:
    - name: build-type
      value: "stage"   # must match enum in pipeline
  pipelineSpec:
    description: |
      This pipeline is ideal for building and verifying file-based catalogs.
    params:
      - name: build-type
        description: Build Type
        enum: ["ci", "nightly", "stage"]
        default: "ci"
    tasks:
      - name: test
        taskSpec:
          params:
            - name: build-type
              type: string
          steps:
            - name: noop
              image: quay.io/rhoai-konflux/alpine:latest
              script: |
                #!/bin/sh
                echo "Parameter value: $(params.build-type)"
        params:
          - name: build-type
            value: $(params.build-type)
    workspaces:
      - name: git-auth
        optional: true
      - name: netrc
        optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhoai-fbc-fragment-v3-0
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
