apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    konflux-release-data/rbc-release-commit: a1b6fc5a4106394181e1fe0ad0a3ea0d18b5b636
  name: rhoai-v2-16-stage-1733156676
  namespace: rhoai-tenant
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-16-components-stage
  snapshot: rhoai-v2-16-1733156676
