apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-421-stage-1772365610
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 2f0ca49cf8cc860f6fce84f00bd4aeee2129f40a
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: stage
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-25-ocp-421-fbc-stage
  snapshot: rhoai-fbc-fragment-ocp-421-1772365610
  data:
    version: 2.25.3
