rhaiOperator:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:5c77a16413ca189badff5b85d8c05b8c57e6f62e18d487c7ffca360587df81fc"
  relatedImages:
    - name: RELATED_IMAGE_ODH_KSERVE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-agent-rhel9@sha256:c483206144888db875372ef63b9dd7f0e4b0e8b4a74e34c9608b578bb80b2703"
    - name: RELATED_IMAGE_ODH_KSERVE_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-controller-rhel9@sha256:99953ceb03c79937a751e7edbaee2f6ad4363d1da2f24f163ae3fe924def1e1a"
    - name: RELATED_IMAGE_ODH_KSERVE_LLMISVC_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-llmisvc-controller-rhel9@sha256:a779c2cd83637edf0299f09caebae9f60a98d34a9573173580e03ce08159e752"
    - name: RELATED_IMAGE_ODH_KSERVE_ROUTER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-router-rhel9@sha256:afdcd76752159f98e51f74ba54da0411ea141a94b4d353ddf85d079ea72c30e9"
    - name: RELATED_IMAGE_ODH_KSERVE_STORAGE_INITIALIZER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-storage-initializer-rhel9@sha256:38f5d561c6224073dd215fbb371c35e6642f1a610ccdad337b32d7a271651393"
    - name: RELATED_IMAGE_RHAIIS_VLLM_CUDA_IMAGE
      value: "registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:ec799bb5eeb7e25b4b25a8917ab5161da6b6f1ab830cbba61bba371cffb0c34d"
    - name: RELATED_IMAGE_RHAIIS_VLLM_ROCM_IMAGE
      value: "registry.redhat.io/rhaiis/vllm-rocm-rhel9@sha256:e345cf9453afae0d3c2afe2f7fb9be8fac772f46593b873e925d38ae2b3ee537"
    - name: RELATED_IMAGE_RHAIIS_VLLM_SPYRE_IMAGE
      value: "registry.redhat.io/rhaiis/vllm-spyre-rhel9@sha256:75f0ea05a92661a33b40efe2a662d976d53c767db18990b433d4a00dd6693aae"
    - name: RELATED_IMAGE_ODH_LLM_D_INFERENCE_SCHEDULER_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-inference-scheduler-rhel9@sha256:905b704f7d9c68af1827bba7c6eefec22d269a9084791952221eb1a1d10e32c7"
    - name: RELATED_IMAGE_ODH_LLM_D_ROUTING_SIDECAR_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-routing-sidecar-rhel9@sha256:a18e0c92de04c6079dcf4fec8a13bc6b924a182b3113e85e81dfaa203001d3f9"
    - name: RELATED_IMAGE_OSE_KUBE_RBAC_PROXY_IMAGE
      value: "registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:9c9c58e55e5d7af5854b2a4322013cd596e712236c6a3e960f4ddde606bd6364"
    - name: RELATED_IMAGE_ODH_LLM_D_KV_CACHE_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-kv-cache-rhel9@sha256:b03558f7bc91fae5115062a33f4235da484b00f9f0c6a3a021ad56f6f55e84f8"

azure:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:5c77a16413ca189badff5b85d8c05b8c57e6f62e18d487c7ffca360587df81fc"

coreweave:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:5c77a16413ca189badff5b85d8c05b8c57e6f62e18d487c7ffca360587df81fc"

