rhaiOperator:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:496a1e3bdcf4eba768e39bca3964476580193b4fdc38a70a4cdd082362be1229"
  relatedImages:
    - name: RELATED_IMAGE_ODH_KSERVE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-agent-rhel9@sha256:cd3e0d0ffcb7a1e8d8c9fcdbb7b26f33c2d578a3d730eb72760f73536fb3e7b0"
    - name: RELATED_IMAGE_ODH_KSERVE_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-controller-rhel9@sha256:812d554ef5da74d72912ce2064c8088e7dc5135ecb0c817b7357bc0994e323f5"
    - name: RELATED_IMAGE_ODH_KSERVE_LLMISVC_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-llmisvc-controller-rhel9@sha256:47a7ec221af35739080ea9e4ada44f139fef390c7f257c327af1205ea954a266"
    - name: RELATED_IMAGE_ODH_KSERVE_ROUTER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-router-rhel9@sha256:da4649d0c36b919930cf54368b52a7ab612c8070a54061d14fe6b1cb08d1be45"
    - name: RELATED_IMAGE_ODH_KSERVE_STORAGE_INITIALIZER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-storage-initializer-rhel9@sha256:813d951ccc5ebec25c48397fc18b63e823656b52bb1657488aa31bd242254490"
    - name: RELATED_IMAGE_RHAII_VLLM_CUDA_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:d3e57d4ca13a17f4d5d1228df4fe47cfe1a9f630250a8b3d26f86d871fdb9e69"
    - name: RELATED_IMAGE_RHAII_VLLM_ROCM_IMAGE
      value: "registry.redhat.io/rhaii/vllm-rocm-rhel9@sha256:cfeac10c571206514c2876f220ce845058511185ebe8944afc32581dc45b34f3"
    - name: RELATED_IMAGE_RHAII_VLLM_SPYRE_IMAGE
      value: "registry.redhat.io/rhaii/vllm-spyre-rhel9@sha256:5c0ed9be230a307d512fa99236b060ac2ecd86973d17c467badc7b5c2d2b5da4"
    - name: RELATED_IMAGE_RHAII_VLLM_CPU_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_RHAII_VLLM_GAUDI_IMAGE
      value: "registry.redhat.io/rhaii/vllm-gaudi-rhel9@sha256:1adc51d99455d90f758d840cb3bb5747ed29585c1b0830c051f7fe5cca3471e6"
    - name: RELATED_IMAGE_ODH_LLM_D_INFERENCE_SCHEDULER_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-inference-scheduler-rhel9@sha256:eb4ac9f497d4690561e76b4d8bce461dec068f574cc42f4152db0f757040e0b2"
    - name: RELATED_IMAGE_ODH_LLM_D_ROUTING_SIDECAR_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-routing-sidecar-rhel9@sha256:b7e29e4abccf79d45078feacdbaa688b18b5b723e4a6441324be7db463df0813"
    - name: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
      value: "registry.redhat.io/rhoai/odh-kube-rbac-proxy-rhel9@sha256:051934be9aa0bc45197d93486edbe7e83d0b72307aa9ef7374a381a41eea8c24"
    - name: RELATED_IMAGE_ODH_LLM_D_KV_CACHE_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-kv-cache-rhel9@sha256:a8771710e86210187e4f1c1c3038491a3e9a1022872db1550b953760fc26f50e"

hooks:
  cliImage: "registry.redhat.io/openshift4/ose-cli-rhel9@sha256:331caf7efdfbf739b1585570e0004ebd8b5301a6977fbc7b2c64a07475354bc8"

azure:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:496a1e3bdcf4eba768e39bca3964476580193b4fdc38a70a4cdd082362be1229"

coreweave:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:496a1e3bdcf4eba768e39bca3964476580193b4fdc38a70a4cdd082362be1229"
