rhaiOperator:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:bfae20e6fbd47c83df4d38469ee65bdb8e8653edad04a6bcf053028e1696f407"
  relatedImages:
    - name: RELATED_IMAGE_ODH_KSERVE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-agent-rhel9@sha256:845b0ee207c1c5a0efa3e29d44c4593fb74c6064affb61672452df94432e70ff"
    - name: RELATED_IMAGE_ODH_KSERVE_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-controller-rhel9@sha256:4449e25f3216e819a156eb03bd39ea85e33609d803a8bd171b4de43a94f73ae7"
    - name: RELATED_IMAGE_ODH_KSERVE_LLMISVC_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-llmisvc-controller-rhel9@sha256:7d3cc2a6f839315975db89bcf861d3cb332a6b23b6878fea1ad1dc4f62a52840"
    - name: RELATED_IMAGE_ODH_KSERVE_ROUTER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-router-rhel9@sha256:cce53bc8074fe174098bcd30f3a1c7bfe46ead836202cfed07d1e7202b151b9d"
    - name: RELATED_IMAGE_ODH_KSERVE_STORAGE_INITIALIZER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-storage-initializer-rhel9@sha256:9dc17506d34e5e744794b4757680c8fa862e26beaad7859c5db8a31c4c57522f"
    - name: RELATED_IMAGE_RHAII_VLLM_CUDA_IMAGE
      value: "registry.redhat.io/rhaii-early-access/vllm-cuda-rhel9@sha256:b798a83042b3fd69b3b7f948914f51403efa328851c3bea539835da7f724f37e"
    - name: RELATED_IMAGE_RHAII_VLLM_ROCM_IMAGE
      value: "registry.redhat.io/rhaii-early-access/vllm-rocm-rhel9@sha256:cc02cc5aa82443ee5a07ebb4c43109216318c0432a05a75e8bde5887558331ca"
    - name: RELATED_IMAGE_RHAII_VLLM_SPYRE_IMAGE
      value: "registry.redhat.io/rhaii-early-access/vllm-spyre-rhel9@sha256:232856ad9086110cd0513162fee7eef246cff4598384fc07dbb465edc1ac9ae6"
    - name: RELATED_IMAGE_RHAII_VLLM_CPU_IMAGE
      value: "registry.redhat.io/rhaii-early-access/vllm-cpu-rhel9@sha256:139e070c2e4e2bc0254aa852b436c35ec2659e8424e228cc4c77a3bc2ddf50b6"
    - name: RELATED_IMAGE_RHAII_VLLM_GAUDI_IMAGE
      value: "registry.redhat.io/rhaii-early-access/vllm-gaudi-rhel9@sha256:1f035dc151e7961f3c1f8081b63fe50c10fbca33ba6fb96a7433b9669c9cd9e5"
    - name: RELATED_IMAGE_ODH_LLM_D_INFERENCE_SCHEDULER_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-inference-scheduler-rhel9@sha256:17f11071fa14cfcc097e69e54f3d1676d54e61132cdbc3e27d96507744dcd2d7"
    - name: RELATED_IMAGE_ODH_LLM_D_ROUTING_SIDECAR_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-routing-sidecar-rhel9@sha256:00d8cd44886422710315a9a15a041180f164c7f14357d08618cd6b79da5b7196"
    - name: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
      value: "registry.redhat.io/rhoai/odh-kube-rbac-proxy-rhel9@sha256:c724a59e82ef84d100588dcc097fa5dccece3a2e84c2aa5596ccdf8a754d15b3"
    - name: RELATED_IMAGE_ODH_LLM_D_KV_CACHE_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-kv-cache-rhel9@sha256:28cbca40c2a72826bc9171ba1b832c0f89cc2d6b59118ff4dc405b90bab66dfa"
    - name: RELATED_IMAGE_ODH_KSERVE_LOCALMODEL_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-localmodel-controller-rhel9@sha256:c2e9d3139f93690d319304809f435614b538780d498ea1c6f532e9cdf24ce6a2"
    - name: RELATED_IMAGE_ODH_KSERVE_LOCALMODELNODE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-localmodelnode-agent-rhel9@sha256:8cb6f33afde64bff7cf456d7925a48a2902dd363322d4c6f5cece1b4f821649e"

hooks:
  cliImage: "registry.redhat.io/openshift4/ose-cli-rhel9@sha256:7434fde9f36d6e638a77977ff1bc2c77d61508227744319497c007649f12fd00"

azure:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:bfae20e6fbd47c83df4d38469ee65bdb8e8653edad04a6bcf053028e1696f407"

coreweave:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:bfae20e6fbd47c83df4d38469ee65bdb8e8653edad04a6bcf053028e1696f407"

aws:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:bfae20e6fbd47c83df4d38469ee65bdb8e8653edad04a6bcf053028e1696f407"
