rhaiOperator:
  image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:aae3949de3d31ecfe338d78cf7002a63e4eaad7ed808f504def2bdba658ba01f"
  relatedImages:
    - name: RELATED_IMAGE_ODH_KSERVE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-agent-rhel9@sha256:d6146218cb2659dd983f2968844f7ec6054c972a1853a8a843cea71229ad9828"
    - name: RELATED_IMAGE_ODH_KSERVE_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-controller-rhel9@sha256:c07c2040a597fac9f085b68b0952d99766963abd4ad36840c7e1020c8684413f"
    - name: RELATED_IMAGE_ODH_KSERVE_LLMISVC_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-llmisvc-controller-rhel9@sha256:98695250305b08bb90042a6ad14d3b1fc6794eb23de916eef126c52b5b6c7e90"
    - name: RELATED_IMAGE_ODH_KSERVE_ROUTER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-router-rhel9@sha256:05f3051141d5b1b6187cab861b7e48101ebfe116ad779f3cf1253699bae7a625"
    - name: RELATED_IMAGE_ODH_KSERVE_STORAGE_INITIALIZER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-storage-initializer-rhel9@sha256:02f4a4963a6f1d16b632988fcdd89ae386d1cd5a235f817a28f57027fd5aa06e"
    - name: RELATED_IMAGE_RHAII_VLLM_CUDA_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:d3e57d4ca13a17f4d5d1228df4fe47cfe1a9f630250a8b3d26f86d871fdb9e69"
    - name: RELATED_IMAGE_RHAII_VLLM_CUDA_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:d3e57d4ca13a17f4d5d1228df4fe47cfe1a9f630250a8b3d26f86d871fdb9e69"
    - name: RELATED_IMAGE_RHAII_VLLM_CUDA_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:d3e57d4ca13a17f4d5d1228df4fe47cfe1a9f630250a8b3d26f86d871fdb9e69"
    - name: RELATED_IMAGE_RHAII_VLLM_ROCM_IMAGE
      value: "registry.redhat.io/rhaii/vllm-rocm-rhel9@sha256:cfeac10c571206514c2876f220ce845058511185ebe8944afc32581dc45b34f3"
    - name: RELATED_IMAGE_RHAII_VLLM_ROCM_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-rocm-rhel9@sha256:cfeac10c571206514c2876f220ce845058511185ebe8944afc32581dc45b34f3"
    - name: RELATED_IMAGE_RHAII_VLLM_ROCM_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-rocm-rhel9@sha256:cfeac10c571206514c2876f220ce845058511185ebe8944afc32581dc45b34f3"
    - name: RELATED_IMAGE_RHAII_VLLM_SPYRE_IMAGE
      value: "registry.redhat.io/rhaii/vllm-spyre-rhel9@sha256:5c0ed9be230a307d512fa99236b060ac2ecd86973d17c467badc7b5c2d2b5da4"
    - name: RELATED_IMAGE_RHAII_VLLM_SPYRE_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-spyre-rhel9@sha256:5c0ed9be230a307d512fa99236b060ac2ecd86973d17c467badc7b5c2d2b5da4"
    - name: RELATED_IMAGE_RHAII_VLLM_SPYRE_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-spyre-rhel9@sha256:5c0ed9be230a307d512fa99236b060ac2ecd86973d17c467badc7b5c2d2b5da4"
    - name: RELATED_IMAGE_RHAII_VLLM_CPU_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_RHAII_VLLM_CPU_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_RHAII_VLLM_CPU_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_ODH_VLLM_CPU_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_ODH_VLLM_CPU_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-cpu-rhel9@sha256:562aeaf7dabfccccf9ecc2d8c0e7d84d813778f146dd9d5c8e3a1d595d07a82c"
    - name: RELATED_IMAGE_RHAII_VLLM_GAUDI_IMAGE
      value: "registry.redhat.io/rhaii/vllm-gaudi-rhel9@sha256:1adc51d99455d90f758d840cb3bb5747ed29585c1b0830c051f7fe5cca3471e6"
    - name: RELATED_IMAGE_RHAII_VLLM_GAUDI_FAST_1_IMAGE
      value: "registry.redhat.io/rhaii/vllm-gaudi-rhel9@sha256:1adc51d99455d90f758d840cb3bb5747ed29585c1b0830c051f7fe5cca3471e6"
    - name: RELATED_IMAGE_RHAII_VLLM_GAUDI_FAST_2_IMAGE
      value: "registry.redhat.io/rhaii/vllm-gaudi-rhel9@sha256:1adc51d99455d90f758d840cb3bb5747ed29585c1b0830c051f7fe5cca3471e6"
    - name: RELATED_IMAGE_ODH_LLM_D_ROUTER_ENDPOINT_PICKER_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-router-endpoint-picker-rhel9@sha256:eec210c18b64145b03b11844655c60533e9bf631c785c5c0657f167eb0f7ca9e"
    - name: RELATED_IMAGE_ODH_LLM_D_ROUTER_DISAGG_SIDECAR_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-router-disagg-sidecar-rhel9@sha256:54a3d1c4f76a474e19831df0534411f3ce003e98f163c270dd10f672f6f06830"
    - name: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
      value: "registry.redhat.io/rhoai/odh-kube-rbac-proxy-rhel9@sha256:d046360f3df8973c85e36b6bf1e3a6e9b163eeaf03c216b15e39e223503c95c7"
    - name: RELATED_IMAGE_ODH_LLM_D_KV_CACHE_IMAGE
      value: "registry.redhat.io/rhoai/odh-llm-d-kv-cache-rhel9@sha256:fe2de5ce8509b9cd097ca5510285456bb173f638d745d65850a96cc8c698f757"
    - name: RELATED_IMAGE_ODH_KSERVE_LOCALMODEL_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-localmodel-controller-rhel9@sha256:a0e4f37c3b537b89af4847895b72d8cb5fd1601609f154208f1f4b43cee85cc2"
    - name: RELATED_IMAGE_ODH_KSERVE_LOCALMODELNODE_AGENT_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-localmodelnode-agent-rhel9@sha256:254166b6bbe4461125c47e02b4712f12b02daa406c91d0c4d9017097e9961be6"
    - name: RELATED_IMAGE_ODH_MAAS_API_IMAGE
      value: "registry.redhat.io/rhoai/odh-maas-api-rhel9@sha256:21145bc7deba07ae2dbd8bf127e2ed495b9c7c6b586094b645c70c6de5cdab7f"
    - name: RELATED_IMAGE_ODH_MAAS_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-maas-controller-rhel9@sha256:f6c937a85546f270935ac90d6a1684be6f18618924705ab0b448a10fff6a49ac"
    - name: RELATED_IMAGE_ODH_AI_GATEWAY_PAYLOAD_PROCESSING_IMAGE
      value: "registry.redhat.io/rhoai/odh-ai-gateway-payload-processing-rhel9@sha256:94525cd51d01fd407e3ac975463a992082fa7f57fb26ac640302df977baaa586"
    - name: RELATED_IMAGE_ODH_KSERVE_MODULE_OPERATOR_IMAGE
      value: "registry.redhat.io/rhoai/odh-kserve-module-operator-rhel9@sha256:aaaab9ae8e62083dbcebcf187d1867be131e19b1d57a2e61b90a298881663daa"
    - name: RELATED_IMAGE_ODH_GUARDRAILS_DETECTOR_HUGGINGFACE_RUNTIME_IMAGE
      value: "registry.redhat.io/rhoai/odh-guardrails-detector-huggingface-runtime-rhel9@sha256:1317e1552acfb0516936e9b2d9c8f0b224fd5cccdaf049568b84c9983069f6d6"
    - name: RELATED_IMAGE_ODH_MLSERVER_IMAGE
      value: "registry.redhat.io/rhoai/odh-mlserver-rhel9@sha256:c800e25e846326380ea755b68480624b5f430e46ba2f13346fa549c95fbf67ce"
    - name: RELATED_IMAGE_ODH_MODEL_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-model-controller-rhel9@sha256:b11390e243c8fb6037587d2c7f16e44c0d7f7594874e6f73a8253a781ad3fb98"
    - name: RELATED_IMAGE_ODH_MODEL_SERVING_API_IMAGE
      value: "registry.redhat.io/rhoai/odh-model-serving-api-rhel9@sha256:a36977a666c06283fb80ceb77e0c75531dacfc01fdcfec4009b83532a86b2eb4"
    - name: RELATED_IMAGE_ODH_OPENVINO_MODEL_SERVER_IMAGE
      value: "registry.redhat.io/rhoai/odh-openvino-model-server-rhel9@sha256:2f2d5ad6b8367248bbf7731440086a24f5167f2da731b44767c2542d9b79c45f"
    - name: RELATED_IMAGE_ODH_VLLM_CPU_IMAGE
      value: "registry.redhat.io/rhoai/odh-vllm-cpu-rhel9@sha256:f7028630031313f01eb27bbed5c7f5c90cb0e1d451c60e710defc472dbcdee0d"
    - name: RELATED_IMAGE_ODH_WORKLOAD_VARIANT_AUTOSCALER_CONTROLLER_IMAGE
      value: "registry.redhat.io/rhoai/odh-workload-variant-autoscaler-controller-rhel9@sha256:33624b68e0cb13af907a5e688dc829b61ee5aad23b0ecc33185e78002c831938"
    - name: RELATED_IMAGE_POSTGRESQL_16_IMAGE
      value: "registry.redhat.io/rhel9/postgresql-16@sha256:cb66eb4b438ce3f9db194dd1948ce25dc4142e789025f214324b7baa3c915c05"
    - name: RELATED_IMAGE_UBI_MINIMAL_IMAGE
      value: "registry.redhat.io/ubi9/ubi-minimal@sha256:907b68736aa798b2d38255b7aa070b2a70acb90803864a40f05d0ec47556ddd0"

hooks:
  cliImage: "registry.redhat.io/openshift4/ose-cli-rhel9@sha256:b33b3e6f296ebaabaebb20d623afdd172d12f1d172cf64ced0cd4612bd7aba93"

azure:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:aae3949de3d31ecfe338d78cf7002a63e4eaad7ed808f504def2bdba658ba01f"

coreweave:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:aae3949de3d31ecfe338d78cf7002a63e4eaad7ed808f504def2bdba658ba01f"

aws:
  cloudManager:
    image: "registry.redhat.io/rhoai/odh-rhel9-operator@sha256:aae3949de3d31ecfe338d78cf7002a63e4eaad7ed808f504def2bdba658ba01f"
