apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v2-21-prod-1749659125
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 09ec727f6789b476672f17c177b4e41fede3e94b
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v2-21
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-21-components-prod
  snapshot: rhoai-v2-21-1749639086
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2025-22871 # https://issues.redhat.com/browse/RHOAIENG-24689
      issues:
        fixed:
          - id: RHOAIENG-27187
            source: issues.redhat.com
          - id: RHOAIENG-26859
            source: issues.redhat.com
          - id: RHOAIENG-26704
            source: issues.redhat.com
          - id: RHOAIENG-26661
            source: issues.redhat.com
          - id: RHOAIENG-26334
            source: issues.redhat.com
          - id: RHOAIENG-26219
            source: issues.redhat.com
          - id: RHOAIENG-26156
            source: issues.redhat.com
          - id: RHOAIENG-26141
            source: issues.redhat.com
          - id: RHOAIENG-26140
            source: issues.redhat.com
          - id: RHOAIENG-26139
            source: issues.redhat.com
          - id: RHOAIENG-26122
            source: issues.redhat.com
          - id: RHOAIENG-26115
            source: issues.redhat.com
          - id: RHOAIENG-26001
            source: issues.redhat.com
          - id: RHOAIENG-25708
            source: issues.redhat.com
          - id: RHOAIENG-25516
            source: issues.redhat.com
          - id: RHOAIENG-25342
            source: issues.redhat.com
          - id: RHOAIENG-25227
            source: issues.redhat.com
          - id: RHOAIENG-25189
            source: issues.redhat.com
          - id: RHOAIENG-25135
            source: issues.redhat.com
          - id: RHOAIENG-25125
            source: issues.redhat.com
          - id: RHOAIENG-24941
            source: issues.redhat.com
          - id: RHOAIENG-24926
            source: issues.redhat.com
          - id: RHOAIENG-24736
            source: issues.redhat.com
          - id: RHOAIENG-24717
            source: issues.redhat.com
          - id: RHOAIENG-24702
            source: issues.redhat.com
          - id: RHOAIENG-24700
            source: issues.redhat.com
          - id: RHOAIENG-24694
            source: issues.redhat.com
          - id: RHOAIENG-24684
            source: issues.redhat.com
          - id: RHOAIENG-24682
            source: issues.redhat.com
          - id: RHOAIENG-24635
            source: issues.redhat.com
          - id: RHOAIENG-24579
            source: issues.redhat.com
          - id: RHOAIENG-24578
            source: issues.redhat.com
          - id: RHOAIENG-24571
            source: issues.redhat.com
          - id: RHOAIENG-24491
            source: issues.redhat.com
          - id: RHOAIENG-24445
            source: issues.redhat.com
          - id: RHOAIENG-24404
            source: issues.redhat.com
          - id: RHOAIENG-24181
            source: issues.redhat.com
          - id: RHOAIENG-24118
            source: issues.redhat.com
          - id: RHOAIENG-24117
            source: issues.redhat.com
          - id: RHOAIENG-24095
            source: issues.redhat.com
          - id: RHOAIENG-23765
            source: issues.redhat.com
          - id: RHOAIENG-23763
            source: issues.redhat.com
          - id: RHOAIENG-23746
            source: issues.redhat.com
          - id: RHOAIENG-23619
            source: issues.redhat.com
          - id: RHOAIENG-23609
            source: issues.redhat.com
          - id: RHOAIENG-23584
            source: issues.redhat.com
          - id: RHOAIENG-23575
            source: issues.redhat.com
          - id: RHOAIENG-23568
            source: issues.redhat.com
          - id: RHOAIENG-23563
            source: issues.redhat.com
          - id: RHOAIENG-23542
            source: issues.redhat.com
          - id: RHOAIENG-23406
            source: issues.redhat.com
          - id: RHOAIENG-23196
            source: issues.redhat.com
          - id: RHOAIENG-23161
            source: issues.redhat.com
          - id: RHOAIENG-22907
            source: issues.redhat.com
          - id: RHOAIENG-22899
            source: issues.redhat.com
          - id: RHOAIENG-22859
            source: issues.redhat.com
          - id: RHOAIENG-22843
            source: issues.redhat.com
          - id: RHOAIENG-22842
            source: issues.redhat.com
          - id: RHOAIENG-22695
            source: issues.redhat.com
          - id: RHOAIENG-22692
            source: issues.redhat.com
          - id: RHOAIENG-22646
            source: issues.redhat.com
          - id: RHOAIENG-22645
            source: issues.redhat.com
          - id: RHOAIENG-22523
            source: issues.redhat.com
          - id: RHOAIENG-22522
            source: issues.redhat.com
          - id: RHOAIENG-22175
            source: issues.redhat.com
          - id: RHOAIENG-22034
            source: issues.redhat.com
          - id: RHOAIENG-22026
            source: issues.redhat.com
          - id: RHOAIENG-21958
            source: issues.redhat.com
          - id: RHOAIENG-21530
            source: issues.redhat.com
          - id: RHOAIENG-21527
            source: issues.redhat.com
          - id: RHOAIENG-21373
            source: issues.redhat.com
          - id: RHOAIENG-20673
            source: issues.redhat.com
          - id: RHOAIENG-20672
            source: issues.redhat.com
          - id: RHOAIENG-20671
            source: issues.redhat.com
          - id: RHOAIENG-20670
            source: issues.redhat.com
          - id: RHOAIENG-20669
            source: issues.redhat.com
          - id: RHOAIENG-20668
            source: issues.redhat.com
          - id: RHOAIENG-20667
            source: issues.redhat.com
          - id: RHOAIENG-20666
            source: issues.redhat.com
          - id: RHOAIENG-20665
            source: issues.redhat.com
          - id: RHOAIENG-20664
            source: issues.redhat.com
          - id: RHOAIENG-20663
            source: issues.redhat.com
          - id: RHOAIENG-20662
            source: issues.redhat.com
          - id: RHOAIENG-20661
            source: issues.redhat.com
          - id: RHOAIENG-20660
            source: issues.redhat.com
          - id: RHOAIENG-20659
            source: issues.redhat.com
          - id: RHOAIENG-20658
            source: issues.redhat.com
          - id: RHOAIENG-20657
            source: issues.redhat.com
          - id: RHOAIENG-20656
            source: issues.redhat.com
          - id: RHOAIENG-20655
            source: issues.redhat.com
          - id: RHOAIENG-20653
            source: issues.redhat.com
          - id: RHOAIENG-20652
            source: issues.redhat.com
          - id: RHOAIENG-20651
            source: issues.redhat.com
          - id: RHOAIENG-20610
            source: issues.redhat.com
          - id: RHOAIENG-20560
            source: issues.redhat.com
          - id: RHOAIENG-20531
            source: issues.redhat.com
          - id: RHOAIENG-20067
            source: issues.redhat.com
          - id: RHOAIENG-19890
            source: issues.redhat.com
          - id: RHOAIENG-19802
            source: issues.redhat.com
          - id: RHOAIENG-19285
            source: issues.redhat.com
          - id: RHOAIENG-18968
            source: issues.redhat.com
          - id: RHOAIENG-18967
            source: issues.redhat.com
          - id: RHOAIENG-18965
            source: issues.redhat.com
          - id: RHOAIENG-18857
            source: issues.redhat.com
          - id: RHOAIENG-17869
            source: issues.redhat.com
          - id: RHOAIENG-17324
            source: issues.redhat.com
          - id: RHOAIENG-17074
            source: issues.redhat.com
          - id: RHOAIENG-17069
            source: issues.redhat.com
          - id: RHOAIENG-16956
            source: issues.redhat.com
          - id: RHOAIENG-16094
            source: issues.redhat.com
          - id: RHOAIENG-15829
            source: issues.redhat.com
          - id: RHOAIENG-14567
            source: issues.redhat.com
          - id: RHOAIENG-14237
            source: issues.redhat.com
          - id: RHOAIENG-13924
            source: issues.redhat.com
          - id: RHOAIENG-13776
            source: issues.redhat.com
          - id: RHOAIENG-11679
            source: issues.redhat.com
          - id: RHOAIENG-11115
            source: issues.redhat.com
          - id: RHOAIENG-6500
            source: issues.redhat.com
          - id: RHOAIENG-553
            source: issues.redhat.com
          - id: RHOAIENG-348
            source: issues.redhat.com
