apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-421-stage-1790697234
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 6698aebba79bf61a3e101b04e9daa04717834284
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: stage
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-421
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-3-ocp-421-fbc-stage
  snapshot: rhoai-fbc-fragment-ocp-421-1790697234
  data:
    version: 3.3.7
