apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1790441160
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 79249f8e302b93c4432dbe9151f2affbefb1096b
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:028ed619d4eb51bc68f882f564803fe5287d0b867196663ae74fb18c0c0a2373
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 9ddde8bcd1c53e692711a9d8a252a3ad8901cbaa