apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1790441160
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 79249f8e302b93c4432dbe9151f2affbefb1096b
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:f2bf234e729b2cf4b20022f5af154d3d6087d0a1355c1ad163e14bafe5d42bb4
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 9ddde8bcd1c53e692711a9d8a252a3ad8901cbaa