apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-420-1790441160
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 79249f8e302b93c4432dbe9151f2affbefb1096b
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-420
  components:
    - name: rhoai-fbc-fragment-ocp-420
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:1f1cd53553d55e77adcfad9860014f7c80492173d6d63bccc7c46fdc576d6207
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 9ddde8bcd1c53e692711a9d8a252a3ad8901cbaa