apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: a03146f0828d8afb4affa75ba1e33dda99734f05
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-16-1742399156
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-16
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:ab95f3fa5d41642368e1e1fd4157234a8b504a17e8e902e4b26647e6288daf4c
    name: odh-operator-bundle-v2-16
    source:
      git:
        revision: d7fc380397b9c2dd531124a9c868a212630d3d5b
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel8@sha256:75a2b003b2d4645996ee1077b33d21637ffbdc45747027ff66ec5a763ff7f636
    name: odh-codeflare-operator-v2-16
    source:
      git:
        revision: 99ed574838601af015223d9ec05b37441cceb1e6
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel8@sha256:13da7e12e135cdb33c89686eca84cffae8ef691fcb4f346622ebd9b47f0a69ee
    name: odh-dashboard-v2-16
    source:
      git:
        revision: e86dad23af1aa3fac40e0d79b2e40c7d64f0726a
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel8@sha256:b7206d9f82da56152c3a4aeb9a3e892d8e1e64679a7e25672e58c29c43745807
    name: odh-data-science-pipelines-argo-argoexec-v2-16
    source:
      git:
        revision: d7c7528d735bb4ef218c9f2d24a54aaa75b2e23c
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8@sha256:57616b9ad657c3495c448e4d5d384747a631a75176c595196ea559f97f128b19
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-16
    source:
      git:
        revision: d7c7528d735bb4ef218c9f2d24a54aaa75b2e23c
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel8@sha256:a9404aa3efe6e6d05ef06ddfc19db17a6fdfa6aba7bcf5450a92a815fb473567
    name: odh-data-science-pipelines-operator-controller-v2-16
    source:
      git:
        revision: 8ec2a9f72eb98b1e1fad0953357e20ac2d555d6a
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel8@sha256:2c659a9ac7fd699084f984a7ed7977ae599805d610a5919dc25ef9c707c8dbce
    name: odh-kf-notebook-controller-v2-16
    source:
      git:
        revision: aeb6ed44a4e7b4876e1e815bdd67b0c0b28b90ed
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel8@sha256:009d616ef478bb3240b6e603bcd8a33348b07d25d5bfab52646ff4a5033500b3
    name: odh-kuberay-operator-controller-v2-16
    source:
      git:
        revision: 2dc46954838c8fb087fcdfc11cb7a2bc7b0af084
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel8@sha256:483768c759314fb9d54ea874a17e21d6ade6e0661a8276680b99d1c825f805c1
    name: odh-kueue-controller-v2-16
    source:
      git:
        revision: f38c4b50ee3d3fa3bbdbc226e38c7606a72a1d25
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel8@sha256:ca4971a047fb7095b1ca4b6e1d8a206af141870a93185da6f4878ae83e4d6792
    name: odh-ml-pipelines-api-server-v2-v2-16
    source:
      git:
        revision: 446645ce3f762ce9713bf3c97ef85d601454592b
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel8@sha256:f194bb513d030df00f4fa7f21c94555310f2180a82ede7cfa7823317a27326de
    name: odh-ml-pipelines-driver-v2-16
    source:
      git:
        revision: 446645ce3f762ce9713bf3c97ef85d601454592b
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel8@sha256:f020bb005a0d2e97b74e5d0acb8b85c64a6c98c98ee4549eafa601c508efb7ca
    name: odh-ml-pipelines-launcher-v2-16
    source:
      git:
        revision: 446645ce3f762ce9713bf3c97ef85d601454592b
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8@sha256:20276a6bf10cd97e02adae529f345b94591b9c9324fa032d79332589b9c56703
    name: odh-ml-pipelines-persistenceagent-v2-v2-16
    source:
      git:
        revision: 446645ce3f762ce9713bf3c97ef85d601454592b
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8@sha256:7dc2a45796803296a214a6c105d49d816e03e01dea82b02966d14502aa17562f
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-16
    source:
      git:
        revision: 446645ce3f762ce9713bf3c97ef85d601454592b
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:e07ea1bf2b5abfbcc34c9b96905e99e57502a4c0f3c8911134946c41fc821974
    name: odh-mlmd-grpc-server-v2-16
    source:
      git:
        revision: 277d189b3777988a82b407de0a994ff2c6739943
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel8@sha256:f738aab1eab25854c93e1d8d4d98100a8ae7bb45a6b83f0326774e4220b1183b
    name: odh-mm-rest-proxy-v2-16
    source:
      git:
        revision: 8d8bcac8df1e1629c2589ccee4d87afd0d99079f
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel8@sha256:56edcb921b1f932aa18d2f307e0fb93d6fce77be9673faaeabb48aef2ec5a8fa
    name: odh-model-controller-v2-16
    source:
      git:
        revision: 4aae62da55c60646d743443b5fd9f5ab7d28a524
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel8@sha256:4bded105a700f61502f710d406bd9fe007dfa5ec242a4f0ff135403c6f812528
    name: odh-model-registry-operator-v2-16
    source:
      git:
        revision: e9f2677e9f1d50c88e3b1a39bb8d9026381ee22a
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel8@sha256:385044823029be8f14ec888a06d540984e00b07f3b12d83015c2ffe9e230bba1
    name: odh-model-registry-v2-16
    source:
      git:
        revision: 292166472ae4d7067001e503c7974333055fd01e
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel8@sha256:dd00d10023eb2140edf80898c5d2d040fcbbd6ab416e9e13b3b9948b8fcf0189
    name: odh-modelmesh-v2-16
    source:
      git:
        revision: e3cee2fd4bb3b0b736c3d369ae18880a61c80b34
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:a57252b4f79eeb57c29e42ce00bf86e6bb4c77386498e928f46ce4ecfd868556
    name: odh-modelmesh-runtime-adapter-v2-16
    source:
      git:
        revision: 96c53b411b957474adbdd97af713eed75a3ad618
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel8@sha256:79f13213f00c14c963ea4089867fa6b76b0bebab3255401a785bd96e77343172
    name: odh-modelmesh-serving-controller-v2-16
    source:
      git:
        revision: 008e28379816840a5d3b7c979aee0bdfd68b2337
        url: https://github.com/red-hat-data-services/modelmesh-serving
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel8@sha256:09f1ea5ad9f9611d4ee01d7906d416db95ba4999171e697301c1954ee9b9da97
    name: odh-notebook-controller-v2-16
    source:
      git:
        revision: aeb6ed44a4e7b4876e1e815bdd67b0c0b28b90ed
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel8-operator@sha256:eabb2277861e1df304f964f407e81a5d5ffa820452eab7d3144492c9615e83dc
    name: odh-operator-v2-16
    source:
      git:
        revision: c635c7e4e7c2358a61b1ecc4d0bbd99d85a256bc
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel8@sha256:3630da5f4d97151b2fe3c28190f790e089dd4297b14423b66099a083c6ac1a1b
    name: odh-training-operator-v2-16
    source:
      git:
        revision: c1f41cad335c028cb7a1072320539ef7551acdbd
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel8@sha256:f3c3e1b1ea417cadd4aca8ffe4ae1bc70f0f1090c675c0650e4e08484aa41d2f
    name: odh-trustyai-service-operator-v2-16
    source:
      git:
        revision: 33718f2da6bd30786c47a8ca163bbbc854013d3d
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel8@sha256:0bb7de116a970b304544099e34c5b04b1738a8098cc6e0e59ca3a4b06a38bc25
    name: odh-trustyai-service-v2-16
    source:
      git:
        revision: 6b3376fd045650ce8f12376bca4e88b02ee079e9
        url: https://github.com/red-hat-data-services/trustyai-explainability
