apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-416-1772365610
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 07c26f7439a298f8c2f78ccd584365daf5faf45f
    konflux-release-data/ocp-version: ocp-416
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-416
  components:
    - name: rhoai-fbc-fragment-ocp-416
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:e8a97a2228bbfcb8afc4c6a435cb232cf0b8e3176e10f16ea4a1b83d6b48da29
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 07950c1a52c68592f55869032686a565bd611bb9