apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-fbc-fragment-ocp-420-prod-1784117523
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 6f6f23fcb48b1981471ad14b8936b8397083adaf
    konflux-release-data/ocp-version: ocp-420
    konflux-release-data/artifact-type: fbc
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-fbc-fragment-ocp-420
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-5-ea-2-ocp-420-fbc-prod
  snapshot: rhoai-fbc-fragment-ocp-420-1784114641
  data:
    version: 3.5.0-ea.2
