apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-421-1781854664
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: e2a5cb14463a313ebd727f7109ee65972274896b
    konflux-release-data/ocp-version: ocp-421
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-421
  components:
    - name: rhoai-fbc-fragment-ocp-421
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:35c84f97124af6a19ab53b551e833329281eedb1176fb8bd229a045b5c18e9d0
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 1d9e25c00720221e722cff995c92dedb1e6397de