apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: rhoai-v3-4-charts-prod-1787747721
  namespace: rhoai-tenant
  labels:
    konflux-release-data/rbc-release-commit: 1d45f4d7c4dba3ba5caec2109e5e1a2da8a5f5d4
    konflux-release-data/actual-rbc-release-commit: 96f9425f07914a9b7719b555f9ca7af78307caf5
    konflux-release-data/artifact-type: charts
    konflux-release-data/environment: prod
    appstudio.openshift.io/application: rhoai-v3-4
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v3-4-charts-prod
  snapshot: rhoai-v3-4-charts-1787574494
  data:
    version: 3.4.4
