apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/environment: stage
    konflux-release-data/rbc-release-commit: a03146f0828d8afb4affa75ba1e33dda99734f05
  name: rhoai-v2-16-stage-1742399156-run4
  namespace: rhoai-tenant
spec:
  gracePeriodDays: 30
  releasePlan: rhoai-onprem-v2-16-components-stage
  snapshot: rhoai-v2-16-1742399156
