name: Test New Workflow
run-name: Test New Workflow
on:
  workflow_dispatch:
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "This is a placeholder workflow to test new workflows."
          echo "The real definition exists in the release branch."
